Json: json::basic_string_key< CharT, Traits, Allocator > Class Template Reference
json::basic_string_key< CharT, Traits, Allocator > Class Template Reference
Representation of a string key for an associative container. It's used as the key of the map in json::object. Supports standard traits and allocators, as well as transparent comparison with c strings and std::basic_strings. If constructed from a static_string, the class will keep a reference to the original string instead of allocating a copy, acting as an string_view, thus saving a heap operation if the user is sure that the static string will outlive the string_key. The string is immutable. After being constructed, it can't be mutated in any way.
#include <string_key.hh>
Public Types
using traits_type = Traits
using allocator_type = Allocator
using value_type = CharT
using pointer = typename std::allocator_traits< Allocator >::pointer
using const_pointer = typename std::allocator_traits< Allocator >::const_pointer
using reference = value_type &
using const_reference = const value_type &
using iterator = const_pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using size_type = typename std::allocator_traits< Allocator >::size_type
using difference_type = typename std::allocator_traits< Allocator >::difference_type
Public Member Functions
basic_string_key (const CharT *s, const Allocator &a=Allocator{})
Constructs a string_key from a character array. The array is copied. Size is computed by Traits::size(s)
basic_string_key (const std::basic_string< CharT, Traits, Allocator > &s)
Constructs a string_key from a std::basic_string.
template<typename OtherAllocator >
basic_string_key (const std::basic_string< CharT, Traits, OtherAllocator > &s, const Allocator &a)
Constructs a string_key from a std::basic_string and a custom allocator.
basic_string_key (std::basic_string< CharT, Traits, Allocator > &&s)
Constructs a string_key from a std::basic_string by move. If s is not a short string, it becomes empty.
basic_string_key (basic_static_string< CharT, Traits > s, const Allocator &a=Allocator{})
Constructs a string_key from a static_string. The string is not copied. string_key will act as a view of the string.
basic_string_key (const basic_string_key &other)
Copy constructor.
basic_string_key (basic_string_key &&other)
Move constructor. Other becomes empty afterwards.
~basic_string_key ()
Destructor frees dynamic memory if the string is not a static string.
Allocator get_allocator () const
Returns the allocator by copy.
const_iterator begin () const noexcept
Returns an iterator to the beginning of the string.
const_iterator cbegin () const noexcept
Returns an iterator to the beginning of the string.
const_iterator end () const noexcept
Returns an iterator to the end of the string.
const_iterator cend () const noexcept
Returns an iterator to the end of the string.
const_reverse_iterator rbegin () const noexcept
Returns a reverse iterator to the beginning of the reversed string (the end of the string)
const_reverse_iterator crbegin () const noexcept
Returns a reverse iterator to the beginning of the reversed string (the end of the string)
const_reverse_iterator rend () const noexcept
Returns a reverse iterator to the end of the reversed string (the beginning of the string)
const_reverse_iterator crend () const noexcept
Returns a reverse iterator to the end of the reversed string (the beginning of the string)
const CharT & operator[] (size_type index) const noexcept
Accesses the character at index.
const CharT & at (size_type index) const
Accesses the character at index. Throws if index > size()
const CharT & front () const noexcept
Accesses the first character.
const CharT & back () const noexcept
Accesses the last character.
const CharT * data () const noexcept
Returns a pointer to the character array.
const CharT * c_str () const noexcept
Accesses the character array.
size_type size () const noexcept
Returns the size of the string. Doesn't take into account the null character.
size_type length () const noexcept
Accesses the length of the string. Same as size()
size_type capacity () const noexcept
Returns the capacity of the allocated buffer.
size_type max_size () const noexcept
Accesses the maximum length the string may have.
bool empty () const noexcept
True if the string is empty.
bool is_view () const noexcept
True if the string is a static string and therefore is not owned by the string_key object.
std::basic_string< CharT, Traits, Allocator > substr (size_type pos=0, size_type count=npos) const
Returns a substring [pos, pos + count) or [pos, size()) if the requested substring extends past the end of the string.
size_type find (const std::basic_string< CharT, Traits, Allocator > &str, size_type pos=0) const
Finds the first substring equal to the given character sequence. Search begins at pos.
size_type find (const CharT *s, size_type pos, size_type count) const
Finds the first substring equal to the given character sequence. Search begins at pos.
size_type find (const CharT *s, size_type pos=0) const
Finds the first substring equal to the given character sequence. Search begins at pos.
size_type find (CharT ch, size_type pos=0) const
Finds the first substring equal to the given character sequence. Search begins at pos.
size_type rfind (const std::basic_string< CharT, Traits, Allocator > &str, size_type pos=0) const
Finds the last substring equal to the given character sequence. Search begins at pos.
size_type rfind (const CharT *s, size_type pos, size_type count) const
Finds the last substring equal to the given character sequence. Search begins at pos.
size_type rfind (const CharT *s, size_type pos=0) const
Finds the last substring equal to the given character sequence. Search begins at pos.
size_type rfind (CharT ch, size_type pos=0) const
Finds the last substring equal to the given character sequence. Search begins at pos.
size_type find_first_of (const std::basic_string< CharT, Traits, Allocator > &str, size_type pos=0) const
Finds the first character equal to any of the characters in the given sequence. Search begins at pos.
size_type find_first_of (const CharT *s, size_type pos, size_type count) const
Finds the first character equal to any of the characters in the given sequence. Search begins at pos.
size_type find_first_of (const CharT *s, size_type pos=0) const
Finds the first character equal to any of the characters in the given sequence. Search begins at pos.
size_type find_first_of (CharT ch, size_type pos=0) const
Finds the first character equal to any of the characters in the given sequence. Search begins at pos.
size_type find_first_not_of (const std::basic_string< CharT, Traits, Allocator > &str, size_type pos=0) const
Finds the first character equal to none of the characters in the given sequence. Search begins at pos.
size_type find_first_not_of (const CharT *s, size_type pos, size_type count) const
Finds the first character equal to none of the characters in the given sequence. Search begins at pos.
size_type find_first_not_of (const CharT *s, size_type pos=0) const
Finds the first character equal to none of the characters in the given sequence. Search begins at pos.
size_type find_first_not_of (CharT ch, size_type pos=0) const
Finds the first character equal to none of the characters in the given sequence. Search begins at pos.
size_type find_last_of (const std::basic_string< CharT, Traits, Allocator > &str, size_type pos=0) const
Finds the last character equal to any of the characters in the given sequence. Search begins at pos.
size_type find_last_of (const CharT *s, size_type pos, size_type count) const
Finds the last character equal to any of the characters in the given sequence. Search begins at pos.
size_type find_last_of (const CharT *s, size_type pos=0) const
Finds the last character equal to any of the characters in the given sequence. Search begins at pos.
size_type find_last_of (CharT ch, size_type pos=0) const
Finds the last character equal to any of the characters in the given sequence. Search begins at pos.
size_type find_last_not_of (const std::basic_string< CharT, Traits, Allocator > &str, size_type pos=0) const
Finds the last character equal to none of the characters in the given sequence. Search begins at pos.
size_type find_last_not_of (const CharT *s, size_type pos, size_type count) const
Finds the last character equal to none of the characters in the given sequence. Search begins at pos.
size_type find_last_not_of (const CharT *s, size_type pos=0) const
Finds the last character equal to none of the characters in the given sequence. Search begins at pos.
size_type find_last_not_of (CharT ch, size_type pos=0) const
Finds the last character equal to none of the characters in the given sequence. Search begins at pos.
operator std::basic_string< CharT, Traits, Allocator > () const
Conversion to std::basic_string.
Static Public Attributes
static constexpr size_type npos = static_cast<size_type>(-1)
Private Member Functions
bool owns_data () const noexcept
True if the string is owned by the object, this is, if it's not a static string.
void free ()
Frees the dynamic memory allocated by the object.
void copy_other (const_pointer src, size_type size)
Makes this string a copy of another. If possible, performs short string optimization. If not, allocates a buffer.
CharT * allocate_buffer (size_type size)
Allocates a buffer for size chars plus the null terminator.
CharT * short_str () noexcept
Accesses the short string buffer casted to a pointer of the character type of the string.
const CharT * short_str () const noexcept
Accesses the short string buffer casted to a pointer of the character type of the string. Const version.
CharT * mutable_str () noexcept
Gives write access to the otherwise const buffer pointed to by str.
bool is_short_str () const noexcept
True if the string is currently stored in place in the string_key object.
constexpr size_type short_str_capacity () const noexcept
Returns number of characters the short string buffer may hold at most.
void make_empty () noexcept
Makes this string a copy of "".
Private Attributes
Allocator alloc
Allocator used to allocate and deallocate dynamic memory.
size_type str_size
Size of the string.
const CharT * str
Pointer to the array of characters.
union {
char short_str_buffer [short_string_buffer_size]
Buffer of characters used to store the string in place if it fits in the buffer.
size_t buffer_capacity = 0
Number of characters that fit in the currently allocated buffer, ignoring the null character.
};
Static Private Attributes
static constexpr size_type short_string_buffer_size = 16
Size of the short string buffer;.
Detailed Description
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>>
class json::basic_string_key< CharT, Traits, Allocator >
Representation of a string key for an associative container. It's used as the key of the map in json::object. Supports standard traits and allocators, as well as transparent comparison with c strings and std::basic_strings. If constructed from a static_string, the class will keep a reference to the original string instead of allocating a copy, acting as an string_view, thus saving a heap operation if the user is sure that the static string will outlive the string_key. The string is immutable. After being constructed, it can't be mutated in any way.
Definition at line 57 of file string_key.hh.
Member Typedef Documentation
allocator_type
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::allocator_type = Allocator
Definition at line 61 of file string_key.hh.
const_iterator
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::const_iterator = const_pointer
Definition at line 68 of file string_key.hh.
const_pointer
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::const_pointer = typename std::allocator_traits<Allocator>::const_pointer
Definition at line 64 of file string_key.hh.
const_reference
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::const_reference = const value_type &
Definition at line 66 of file string_key.hh.
const_reverse_iterator
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 70 of file string_key.hh.
difference_type
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::difference_type = typename std::allocator_traits<Allocator>::difference_type
Definition at line 72 of file string_key.hh.
iterator
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::iterator = const_pointer
Definition at line 67 of file string_key.hh.
pointer
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::pointer = typename std::allocator_traits<Allocator>::pointer
Definition at line 63 of file string_key.hh.
reference
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::reference = value_type &
Definition at line 65 of file string_key.hh.
reverse_iterator
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 69 of file string_key.hh.
size_type
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::size_type = typename std::allocator_traits<Allocator>::size_type
Definition at line 71 of file string_key.hh.
traits_type
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::traits_type = Traits
Definition at line 60 of file string_key.hh.
value_type
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> using json::basic_string_key< CharT, Traits, Allocator >::value_type = CharT
Definition at line 62 of file string_key.hh.
Constructor & Destructor Documentation
basic_string_key() [1/7]
template<typename CharT, typename Traits , typename Allocator> json::basic_string_key< CharT, Traits, Allocator >::basic_string_key (const CharT * s, const Allocator & a = Allocator{})
Constructs a string_key from a character array. The array is copied. Size is computed by Traits::size(s)
Definition at line 31 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::copy_other().
     : alloc{ a }
   {
     copy_other(s, Traits::length(s));
   }
basic_string_key() [2/7]
template<typename CharT, typename Traits, typename Allocator> json::basic_string_key< CharT, Traits, Allocator >::basic_string_key (const std::basic_string< CharT, Traits, Allocator > & s)
Constructs a string_key from a std::basic_string.
Definition at line 38 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::copy_other().
     : alloc{ s.get_allocator() }
   {
     copy_other(s.c_str(), s.size());
   }
basic_string_key() [3/7]
template<typename CharT, typename Traits, typename Allocator> template<typename OtherAllocator > json::basic_string_key< CharT, Traits, Allocator >::basic_string_key (const std::basic_string< CharT, Traits, OtherAllocator > & s, const Allocator & a)
Constructs a string_key from a std::basic_string and a custom allocator.
Definition at line 46 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::copy_other().
     : alloc{ a }
   {
     copy_other(s.c_str(), s.size());
   }
basic_string_key() [4/7]
template<typename CharT, typename Traits, typename Allocator> json::basic_string_key< CharT, Traits, Allocator >::basic_string_key (std::basic_string< CharT, Traits, Allocator > && s)
Constructs a string_key from a std::basic_string by move. If s is not a short string, it becomes empty.
Definition at line 53 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::buffer_capacity, json::basic_string_key< CharT, Traits, Allocator >::copy_other(), json::points_inside(), json::release(), json::basic_string_key< CharT, Traits, Allocator >::str, and json::basic_string_key< CharT, Traits, Allocator >::str_size.
     : alloc{ s.get_allocator() }
   {
     // If s is a short string
     if (points_inside(s.c_str(), s))
       copy_other(s.c_str(), s.size());
     else
     {
       buffer_capacity = s.capacity();
       str_size = s.size();
       str = release(s);
     }
   }
basic_string_key() [5/7]
template<typename CharT, typename Traits, typename Allocator> json::basic_string_key< CharT, Traits, Allocator >::basic_string_key (basic_static_string< CharT, Traits > s, const Allocator & a = Allocator{})
Constructs a string_key from a static_string. The string is not copied. string_key will act as a view of the string.
Definition at line 68 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::buffer_capacity, json::basic_string_key< CharT, Traits, Allocator >::str, and json::basic_string_key< CharT, Traits, Allocator >::str_size.
     : alloc{ a }
     , str_size{ s.size() }
     , str{ s.c_str() }
     , buffer_capacity{ 0 }
   {}
basic_string_key() [6/7]
template<typename CharT, typename Traits, typename Allocator> json::basic_string_key< CharT, Traits, Allocator >::basic_string_key (const basic_string_key< CharT, Traits, Allocator > & other)
Copy constructor.
Definition at line 76 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::alloc, json::basic_string_key< CharT, Traits, Allocator >::copy_other(), json::basic_string_key< CharT, Traits, Allocator >::str, and json::basic_string_key< CharT, Traits, Allocator >::str_size.
     : alloc{ other.alloc }
     , str_size{ other.str_size }
     , str{}
   {
     if (other.owns_data())
       copy_other(other.str, other.str_size);
     else
       str = other.str;
   }
basic_string_key() [7/7]
template<typename CharT, typename Traits, typename Allocator> json::basic_string_key< CharT, Traits, Allocator >::basic_string_key (basic_string_key< CharT, Traits, Allocator > && other)
Move constructor. Other becomes empty afterwards.
Definition at line 88 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::buffer_capacity, json::basic_string_key< CharT, Traits, Allocator >::copy_other(), json::basic_string_key< CharT, Traits, Allocator >::str, and json::basic_string_key< CharT, Traits, Allocator >::str_size.
     : alloc{ std::move(other.alloc) }
     , str_size{ std::move(other.str_size) }
     , str{}
   {
     if (other.is_short_str())
       copy_other(other.str, other.str_size);
     else
     {
       str = other.str;
       buffer_capacity = other.buffer_capacity;
     }
     other.make_empty();
   }
~basic_string_key()
template<typename CharT , typename Traits , typename Allocator > json::basic_string_key< CharT, Traits, Allocator >::~basic_string_key ()
Destructor frees dynamic memory if the string is not a static string.
Definition at line 105 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::free().
   {
     free();
   }
Member Function Documentation
allocate_buffer()
template<typename CharT , typename Traits , typename Allocator > CharT * json::basic_string_key< CharT, Traits, Allocator >::allocate_buffer (size_type size) private
Allocates a buffer for size chars plus the null terminator.
Definition at line 456 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::alloc, json::basic_string_key< CharT, Traits, Allocator >::buffer_capacity, json::basic_string_key< CharT, Traits, Allocator >::short_str(), json::basic_string_key< CharT, Traits, Allocator >::short_str_capacity(), and json::basic_string_key< CharT, Traits, Allocator >::size().
Referenced by json::basic_string_key< CharT, Traits, Allocator >::copy_other().
   {
     // If the string fits in the short string buffer, use that
     if (size <= short_str_capacity())
       return short_str();
     // Otherwise allocate a new buffer big enough to fit the string and the null character
     else
     {
       buffer_capacity = size;
       return std::allocator_traits<Allocator>::allocate(alloc, size + 1);
     }
   }
at()
template<typename CharT , typename Traits , typename Allocator > const CharT & json::basic_string_key< CharT, Traits, Allocator >::at (size_type index) const
Accesses the character at index. Throws if index > size()
Definition at line 171 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::data(), and json::basic_string_key< CharT, Traits, Allocator >::size().
   {
     if (index >= size())
       throw std::out_of_range{ "string subscript out of range" };
     return data()[index];
   }
back()
template<typename CharT , typename Traits , typename Allocator > const CharT & json::basic_string_key< CharT, Traits, Allocator >::back () const noexcept
Accesses the last character.
Definition at line 185 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::data(), and json::basic_string_key< CharT, Traits, Allocator >::size().
   {
     return data()[size() - 1];
   }
begin()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::const_iterator json::basic_string_key< CharT, Traits, Allocator >::begin () const noexcept
Returns an iterator to the beginning of the string.
Definition at line 117 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::cbegin().
Referenced by json::basic_string_key< CharT, Traits, Allocator >::find(), json::basic_string_key< CharT, Traits, Allocator >::find_first_of(), json::basic_string_key< CharT, Traits, Allocator >::operator std::basic_string< CharT, Traits, Allocator >(), and json::basic_string_key< CharT, Traits, Allocator >::substr().
   {
     return cbegin();
   }
c_str()
template<typename CharT , typename Traits , typename Allocator > const CharT * json::basic_string_key< CharT, Traits, Allocator >::c_str () const noexcept
Accesses the character array.
Definition at line 197 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::data().
Referenced by json::operator<(), json::operator<=(), and json::writer::write_string().
   {
     return data();
   }
capacity()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::capacity () const noexcept
Returns the capacity of the allocated buffer.
Definition at line 215 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::buffer_capacity, json::basic_string_key< CharT, Traits, Allocator >::is_short_str(), and json::basic_string_key< CharT, Traits, Allocator >::short_str_capacity().
   {
     if (is_short_str())
       return short_str_capacity();
     else
       return buffer_capacity;
   }
cbegin()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::const_iterator json::basic_string_key< CharT, Traits, Allocator >::cbegin () const noexcept
Returns an iterator to the beginning of the string.
Definition at line 123 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::data().
Referenced by json::basic_string_key< CharT, Traits, Allocator >::begin().
   {
     return data();
   }
cend()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::const_iterator json::basic_string_key< CharT, Traits, Allocator >::cend () const noexcept
Returns an iterator to the end of the string.
Definition at line 135 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::data(), and json::basic_string_key< CharT, Traits, Allocator >::size().
Referenced by json::basic_string_key< CharT, Traits, Allocator >::end().
   {
     return data() + size();
   }
copy_other()
template<typename CharT , typename Traits , typename Allocator > void json::basic_string_key< CharT, Traits, Allocator >::copy_other (const_pointer src, size_type size) private
Makes this string a copy of another. If possible, performs short string optimization. If not, allocates a buffer.
Definition at line 447 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::allocate_buffer(), json::basic_string_key< CharT, Traits, Allocator >::size(), json::basic_string_key< CharT, Traits, Allocator >::str, and json::basic_string_key< CharT, Traits, Allocator >::str_size.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::basic_string_key().
   {
     CharT * buffer = allocate_buffer(size);
     Traits::copy(buffer, src, size + 1);
     str = buffer;
     str_size = size;
   }
crbegin()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::const_reverse_iterator json::basic_string_key< CharT, Traits, Allocator >::crbegin () const noexcept
Returns a reverse iterator to the beginning of the reversed string (the end of the string)
Definition at line 147 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::data(), and json::basic_string_key< CharT, Traits, Allocator >::size().
Referenced by json::basic_string_key< CharT, Traits, Allocator >::rbegin().
   {
     return const_reverse_iterator{ data() + size() };
   }
crend()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::const_reverse_iterator json::basic_string_key< CharT, Traits, Allocator >::crend () const noexcept
Returns a reverse iterator to the end of the reversed string (the beginning of the string)
Definition at line 159 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::data().
Referenced by json::basic_string_key< CharT, Traits, Allocator >::rend().
   {
     return const_reverse_iterator{ data() };
   }
data()
template<typename CharT , typename Traits , typename Allocator > const CharT * json::basic_string_key< CharT, Traits, Allocator >::data () const noexcept
Returns a pointer to the character array.
Definition at line 191 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::str.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::at(), json::basic_string_key< CharT, Traits, Allocator >::back(), json::basic_string_key< CharT, Traits, Allocator >::c_str(), json::basic_string_key< CharT, Traits, Allocator >::cbegin(), json::basic_string_key< CharT, Traits, Allocator >::cend(), json::basic_string_key< CharT, Traits, Allocator >::crbegin(), json::basic_string_key< CharT, Traits, Allocator >::crend(), json::basic_string_key< CharT, Traits, Allocator >::find_first_not_of(), json::basic_string_key< CharT, Traits, Allocator >::find_last_not_of(), json::basic_string_key< CharT, Traits, Allocator >::front(), and json::basic_string_key< CharT, Traits, Allocator >::operator[]().
   {
     return str;
   }
empty()
template<typename CharT , typename Traits , typename Allocator > bool json::basic_string_key< CharT, Traits, Allocator >::empty () const noexcept
True if the string is empty.
Definition at line 230 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::size().
   {
     return size() == 0;
   }
end()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::const_iterator json::basic_string_key< CharT, Traits, Allocator >::end () const noexcept
Returns an iterator to the end of the string.
Definition at line 129 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::cend().
Referenced by json::basic_string_key< CharT, Traits, Allocator >::find(), json::basic_string_key< CharT, Traits, Allocator >::find_first_of(), and json::basic_string_key< CharT, Traits, Allocator >::operator std::basic_string< CharT, Traits, Allocator >().
   {
     return cend();
   }
find() [1/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find (const std::basic_string< CharT, Traits, Allocator > & str, size_type pos = 0) const
Finds the first substring equal to the given character sequence. Search begins at pos.
Definition at line 253 of file string_key.inl.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::find().
   {
     return find(s.c_str(), pos, s.size());
   }
find() [2/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find (const CharT * s, size_type pos, size_type count) const
Finds the first substring equal to the given character sequence. Search begins at pos.
Definition at line 259 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::begin(), json::basic_string_key< CharT, Traits, Allocator >::end(), and json::basic_string_key< CharT, Traits, Allocator >::npos.
   {
     const auto it = std::search(begin() + pos, end(), s, s + count, Traits::eq);
     if (it == end())
       return npos;
     else
       return it - begin();
   }
find() [3/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find (const CharT * s, size_type pos = 0) const
Finds the first substring equal to the given character sequence. Search begins at pos.
Definition at line 269 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::find().
   {
     return find(s, pos, Traits::length(s));
   }
find() [4/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find (CharT ch, size_type pos = 0) const
Finds the first substring equal to the given character sequence. Search begins at pos.
Definition at line 275 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::find().
   {
     return find(&ch, pos, 1);
   }
find_first_not_of() [1/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_first_not_of (const std::basic_string< CharT, Traits, Allocator > & str, size_type pos = 0) const
Finds the first character equal to none of the characters in the given sequence. Search begins at pos.
Definition at line 340 of file string_key.inl.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::find_first_not_of().
   {
     return find_first_not_of(s.c_str(), pos, s.size());
   }
find_first_not_of() [2/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_first_not_of (const CharT * s, size_type pos, size_type count) const
Finds the first character equal to none of the characters in the given sequence. Search begins at pos.
Definition at line 346 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::data(), json::basic_string_key< CharT, Traits, Allocator >::npos, and json::basic_string_key< CharT, Traits, Allocator >::size().
   {
     for (size_type i = pos; i < size(); ++i)
       if (std::none_of(s, s + count, [&](CharT ch) { return Traits::eq(ch, data()[i]); }))
         return i;
     return npos;
   }
find_first_not_of() [3/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_first_not_of (const CharT * s, size_type pos = 0) const
Finds the first character equal to none of the characters in the given sequence. Search begins at pos.
Definition at line 355 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::find_first_not_of().
   {
     return find_first_not_of(s, pos, Traits::length(s));
   }
find_first_not_of() [4/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_first_not_of (CharT ch, size_type pos = 0) const
Finds the first character equal to none of the characters in the given sequence. Search begins at pos.
Definition at line 361 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::find_first_not_of().
   {
     return find_first_not_of(&ch, pos, 1);
   }
find_first_of() [1/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_first_of (const std::basic_string< CharT, Traits, Allocator > & str, size_type pos = 0) const
Finds the first character equal to any of the characters in the given sequence. Search begins at pos.
Definition at line 312 of file string_key.inl.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::find_first_of().
   {
     return find_first_of(s.c_str(), pos, s.size());
   }
find_first_of() [2/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_first_of (const CharT * s, size_type pos, size_type count) const
Finds the first character equal to any of the characters in the given sequence. Search begins at pos.
Definition at line 318 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::begin(), json::basic_string_key< CharT, Traits, Allocator >::end(), and json::basic_string_key< CharT, Traits, Allocator >::npos.
   {
     const auto it = std::find_first_of(begin() + pos, end(), s, s + count, Traits::eq);
     if (it == end())
       return npos;
     else
       return it - begin();
   }
find_first_of() [3/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_first_of (const CharT * s, size_type pos = 0) const
Finds the first character equal to any of the characters in the given sequence. Search begins at pos.
Definition at line 328 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::find_first_of().
   {
     return find_first_of(s, pos, Traits::length(s));
   }
find_first_of() [4/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_first_of (CharT ch, size_type pos = 0) const
Finds the first character equal to any of the characters in the given sequence. Search begins at pos.
Definition at line 334 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::find_first_of().
   {
     return find_first_of(&ch, pos, 1);
   }
find_last_not_of() [1/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_last_not_of (const std::basic_string< CharT, Traits, Allocator > & str, size_type pos = 0) const
Finds the last character equal to none of the characters in the given sequence. Search begins at pos.
Definition at line 398 of file string_key.inl.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::find_last_not_of().
   {
     return find_last_not_of(s.c_str(), pos, s.size());
   }
find_last_not_of() [2/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_last_not_of (const CharT * s, size_type pos, size_type count) const
Finds the last character equal to none of the characters in the given sequence. Search begins at pos.
Definition at line 404 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::data(), json::basic_string_key< CharT, Traits, Allocator >::npos, and json::basic_string_key< CharT, Traits, Allocator >::size().
   {
     for (size_type i = size() - 1 - pos; i != npos; --i)
       if (std::none_of(s, s + count, [&](CharT ch) { return Traits::eq(ch, data()[i]); }))
         return i;
     return npos;
   }
find_last_not_of() [3/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_last_not_of (const CharT * s, size_type pos = 0) const
Finds the last character equal to none of the characters in the given sequence. Search begins at pos.
Definition at line 413 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::find_last_not_of().
   {
     return find_last_not_of(s, pos, Traits::length(s));
   }
find_last_not_of() [4/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_last_not_of (CharT ch, size_type pos = 0) const
Finds the last character equal to none of the characters in the given sequence. Search begins at pos.
Definition at line 419 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::find_last_not_of().
   {
     return find_last_not_of(&ch, pos, 1);
   }
find_last_of() [1/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_last_of (const std::basic_string< CharT, Traits, Allocator > & str, size_type pos = 0) const
Finds the last character equal to any of the characters in the given sequence. Search begins at pos.
Definition at line 367 of file string_key.inl.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::find_last_of().
   {
     return find_last_of(s.c_str(), pos, s.size());
   }
find_last_of() [2/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_last_of (const CharT * s, size_type pos, size_type count) const
Finds the last character equal to any of the characters in the given sequence. Search begins at pos.
Definition at line 373 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::npos, json::basic_string_key< CharT, Traits, Allocator >::rbegin(), and json::basic_string_key< CharT, Traits, Allocator >::rend().
   {
     const reverse_iterator s_begin{ s + count };
     const reverse_iterator s_end{ s };
     const auto it = std::find_first_of(rbegin() + pos, rend(), s_begin, s_end, Traits::eq);
     if (it == rend())
       return npos;
     else
       return rend() - it - 1;
   }
find_last_of() [3/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_last_of (const CharT * s, size_type pos = 0) const
Finds the last character equal to any of the characters in the given sequence. Search begins at pos.
Definition at line 386 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::find_last_of().
   {
     return find_last_of(s, pos, Traits::length(s));
   }
find_last_of() [4/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::find_last_of (CharT ch, size_type pos = 0) const
Finds the last character equal to any of the characters in the given sequence. Search begins at pos.
Definition at line 392 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::find_last_of().
   {
     return find_last_of(&ch, pos, 1);
   }
free()
template<typename CharT , typename Traits , typename Allocator > void json::basic_string_key< CharT, Traits, Allocator >::free () private
Frees the dynamic memory allocated by the object.
Definition at line 439 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::alloc, json::basic_string_key< CharT, Traits, Allocator >::buffer_capacity, json::basic_string_key< CharT, Traits, Allocator >::is_short_str(), json::basic_string_key< CharT, Traits, Allocator >::mutable_str(), and json::basic_string_key< CharT, Traits, Allocator >::owns_data().
Referenced by json::basic_string_key< CharT, Traits, Allocator >::~basic_string_key().
   {
     // Free memory only if this is not a view and if this is not a short string
     if (owns_data() && !is_short_str())
       std::allocator_traits<Allocator>::deallocate(alloc, mutable_str(), buffer_capacity + 1);
   }
front()
template<typename CharT , typename Traits , typename Allocator > const CharT & json::basic_string_key< CharT, Traits, Allocator >::front () const noexcept
Accesses the first character.
Definition at line 179 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::data().
   {
     return data()[0];
   }
get_allocator()
template<typename CharT , typename Traits , typename Allocator > Allocator json::basic_string_key< CharT, Traits, Allocator >::get_allocator () const
Returns the allocator by copy.
Definition at line 111 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::alloc.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::max_size(), json::basic_string_key< CharT, Traits, Allocator >::operator std::basic_string< CharT, Traits, Allocator >(), and json::basic_string_key< CharT, Traits, Allocator >::substr().
   {
     return alloc;
   }
is_short_str()
template<typename CharT , typename Traits , typename Allocator > bool json::basic_string_key< CharT, Traits, Allocator >::is_short_str () const private noexcept
True if the string is currently stored in place in the string_key object.
Definition at line 488 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::short_str(), and json::basic_string_key< CharT, Traits, Allocator >::str.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::capacity(), json::basic_string_key< CharT, Traits, Allocator >::free(), and json::basic_string_key< CharT, Traits, Allocator >::owns_data().
   {
     return str == short_str();
   }
is_view()
template<typename CharT , typename Traits , typename Allocator > bool json::basic_string_key< CharT, Traits, Allocator >::is_view () const noexcept
True if the string is a static string and therefore is not owned by the string_key object.
Definition at line 236 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::owns_data().
   {
     return !owns_data();
   }
length()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::length () const noexcept
Accesses the length of the string. Same as size()
Definition at line 209 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::size().
Referenced by json::string_key_literals::operator"" _sk(), and json::string_key_literals::operator"" _ss().
   {
     return size();
   }
make_empty()
template<typename CharT , typename Traits , typename Allocator > void json::basic_string_key< CharT, Traits, Allocator >::make_empty () private noexcept
Makes this string a copy of "".
Definition at line 500 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::short_str(), json::basic_string_key< CharT, Traits, Allocator >::str, and json::basic_string_key< CharT, Traits, Allocator >::str_size.
   {
     const CharT c = CharT{}; // Null character
     str = short_str();
     str_size = 0;
     Traits::copy(short_str(), &c, 1);
   }
max_size()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::max_size () const noexcept
Accesses the maximum length the string may have.
Definition at line 224 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::get_allocator().
   {
     return std::allocator_traits<Allocator>::max_size(get_allocator());
   }
mutable_str()
template<typename CharT , typename Traits , typename Allocator > CharT * json::basic_string_key< CharT, Traits, Allocator >::mutable_str () private noexcept
Gives write access to the otherwise const buffer pointed to by str.
Definition at line 482 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::str.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::free().
   {
     return const_cast<CharT *>(str);
   }
operator std::basic_string< CharT, Traits, Allocator >()
template<typename CharT , typename Traits , typename Allocator > json::basic_string_key< CharT, Traits, Allocator >::operator std::basic_string< CharT, Traits, Allocator > () const explicit
Conversion to std::basic_string.
Definition at line 425 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::begin(), json::basic_string_key< CharT, Traits, Allocator >::end(), and json::basic_string_key< CharT, Traits, Allocator >::get_allocator().
   {
     return std::basic_string<CharT, Traits, Allocator>{ begin(), end(), get_allocator() };
   }
operator[]()
template<typename CharT , typename Traits , typename Allocator > const CharT & json::basic_string_key< CharT, Traits, Allocator >::operator[] (size_type index) const noexcept
Accesses the character at index.
Definition at line 165 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::data().
   {
     return data()[index];
   }
owns_data()
template<typename CharT , typename Traits , typename Allocator > bool json::basic_string_key< CharT, Traits, Allocator >::owns_data () const private noexcept
True if the string is owned by the object, this is, if it's not a static string.
Definition at line 433 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::buffer_capacity, and json::basic_string_key< CharT, Traits, Allocator >::is_short_str().
Referenced by json::basic_string_key< CharT, Traits, Allocator >::free(), and json::basic_string_key< CharT, Traits, Allocator >::is_view().
   {
     return is_short_str() || buffer_capacity > 0;
   }
rbegin()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::const_reverse_iterator json::basic_string_key< CharT, Traits, Allocator >::rbegin () const noexcept
Returns a reverse iterator to the beginning of the reversed string (the end of the string)
Definition at line 141 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::crbegin().
Referenced by json::basic_string_key< CharT, Traits, Allocator >::find_last_of(), and json::basic_string_key< CharT, Traits, Allocator >::rfind().
   {
     return crbegin();
   }
rend()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::const_reverse_iterator json::basic_string_key< CharT, Traits, Allocator >::rend () const noexcept
Returns a reverse iterator to the end of the reversed string (the beginning of the string)
Definition at line 153 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::crend().
Referenced by json::basic_string_key< CharT, Traits, Allocator >::find_last_of(), and json::basic_string_key< CharT, Traits, Allocator >::rfind().
   {
     return crend();
   }
rfind() [1/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::rfind (const std::basic_string< CharT, Traits, Allocator > & str, size_type pos = 0) const
Finds the last substring equal to the given character sequence. Search begins at pos.
Definition at line 281 of file string_key.inl.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::rfind().
   {
     return rfind(s.c_str(), pos, s.size());
   }
rfind() [2/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::rfind (const CharT * s, size_type pos, size_type count) const
Finds the last substring equal to the given character sequence. Search begins at pos.
Definition at line 287 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::npos, json::basic_string_key< CharT, Traits, Allocator >::rbegin(), and json::basic_string_key< CharT, Traits, Allocator >::rend().
   {
     const reverse_iterator s_begin{ s + count };
     const reverse_iterator s_end{ s };
     const auto it = std::search(rbegin() + pos, rend(), s_begin, s_end, Traits::eq);
     if (it == rend())
       return npos;
     else
       return rend() - it - count;
   }
rfind() [3/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::rfind (const CharT * s, size_type pos = 0) const
Finds the last substring equal to the given character sequence. Search begins at pos.
Definition at line 300 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::rfind().
   {
     return rfind(s, pos, Traits::length(s));
   }
rfind() [4/4]
template<typename CharT, typename Traits, typename Allocator> basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::rfind (CharT ch, size_type pos = 0) const
Finds the last substring equal to the given character sequence. Search begins at pos.
Definition at line 306 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::rfind().
   {
     return rfind(&ch, pos, 1);
   }
short_str() [1/2]
template<typename CharT , typename Traits , typename Allocator > CharT * json::basic_string_key< CharT, Traits, Allocator >::short_str () private noexcept
Accesses the short string buffer casted to a pointer of the character type of the string.
Definition at line 470 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::short_str_buffer.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::allocate_buffer(), json::basic_string_key< CharT, Traits, Allocator >::is_short_str(), and json::basic_string_key< CharT, Traits, Allocator >::make_empty().
   {
     return reinterpret_cast<CharT *>(short_str_buffer);
   }
short_str() [2/2]
template<typename CharT , typename Traits , typename Allocator > const CharT * json::basic_string_key< CharT, Traits, Allocator >::short_str () const private noexcept
Accesses the short string buffer casted to a pointer of the character type of the string. Const version.
Definition at line 476 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::short_str_buffer.
   {
     return reinterpret_cast<const CharT *>(short_str_buffer);
   }
short_str_capacity()
template<typename CharT , typename Traits , typename Allocator > constexpr basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::short_str_capacity () const private noexcept
Returns number of characters the short string buffer may hold at most.
Definition at line 494 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::short_string_buffer_size.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::allocate_buffer(), and json::basic_string_key< CharT, Traits, Allocator >::capacity().
   {
     return (short_string_buffer_size / sizeof(CharT)) - 1;
   }
size()
template<typename CharT , typename Traits , typename Allocator > basic_string_key< CharT, Traits, Allocator >::size_type json::basic_string_key< CharT, Traits, Allocator >::size () const noexcept
Returns the size of the string. Doesn't take into account the null character.
Definition at line 203 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::str_size.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::allocate_buffer(), json::basic_string_key< CharT, Traits, Allocator >::at(), json::basic_string_key< CharT, Traits, Allocator >::back(), json::basic_string_key< CharT, Traits, Allocator >::cend(), json::basic_string_key< CharT, Traits, Allocator >::copy_other(), json::basic_string_key< CharT, Traits, Allocator >::crbegin(), json::basic_string_key< CharT, Traits, Allocator >::empty(), json::basic_string_key< CharT, Traits, Allocator >::find_first_not_of(), json::basic_string_key< CharT, Traits, Allocator >::find_last_not_of(), json::basic_string_key< CharT, Traits, Allocator >::length(), json::basic_string_key< CharT, Traits, Allocator >::substr(), and json::writer::write_string().
   {
     return str_size;
   }
substr()
template<typename CharT , typename Traits , typename Allocator > std::basic_string< CharT, Traits, Allocator > json::basic_string_key< CharT, Traits, Allocator >::substr (size_type pos = 0, size_type count = npos) const
Returns a substring [pos, pos + count) or [pos, size()) if the requested substring extends past the end of the string.
Definition at line 242 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::begin(), json::basic_string_key< CharT, Traits, Allocator >::get_allocator(), json::basic_string_key< CharT, Traits, Allocator >::npos, and json::basic_string_key< CharT, Traits, Allocator >::size().
   {
     const size_type first = std::min(pos, size());
     const size_type last = count == npos
       ? size()
       : std::min(pos + count, size());
     return std::basic_string<CharT, Traits, Allocator>{ begin() + first, begin() + last, get_allocator() };
   }
Member Data Documentation
@1
union { ... }
alloc
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> Allocator json::basic_string_key< CharT, Traits, Allocator >::alloc private
Allocator used to allocate and deallocate dynamic memory.
Definition at line 225 of file string_key.hh.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::allocate_buffer(), json::basic_string_key< CharT, Traits, Allocator >::basic_string_key(), json::basic_string_key< CharT, Traits, Allocator >::free(), and json::basic_string_key< CharT, Traits, Allocator >::get_allocator().
buffer_capacity
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> size_t json::basic_string_key< CharT, Traits, Allocator >::buffer_capacity = 0
Number of characters that fit in the currently allocated buffer, ignoring the null character.
Definition at line 231 of file string_key.hh.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::allocate_buffer(), json::basic_string_key< CharT, Traits, Allocator >::basic_string_key(), json::basic_string_key< CharT, Traits, Allocator >::capacity(), json::basic_string_key< CharT, Traits, Allocator >::free(), and json::basic_string_key< CharT, Traits, Allocator >::owns_data().
npos
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> constexpr size_type json::basic_string_key< CharT, Traits, Allocator >::npos = static_cast<size_type>(-1) static
Definition at line 74 of file string_key.hh.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::find(), json::basic_string_key< CharT, Traits, Allocator >::find_first_not_of(), json::basic_string_key< CharT, Traits, Allocator >::find_first_of(), json::basic_string_key< CharT, Traits, Allocator >::find_last_not_of(), json::basic_string_key< CharT, Traits, Allocator >::find_last_of(), json::basic_string_key< CharT, Traits, Allocator >::rfind(), and json::basic_string_key< CharT, Traits, Allocator >::substr().
short_str_buffer
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> char json::basic_string_key< CharT, Traits, Allocator >::short_str_buffer[short_string_buffer_size]
Buffer of characters used to store the string in place if it fits in the buffer.
Definition at line 230 of file string_key.hh.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::short_str().
short_string_buffer_size
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> constexpr size_type json::basic_string_key< CharT, Traits, Allocator >::short_string_buffer_size = 16 static private
Size of the short string buffer;.
Definition at line 223 of file string_key.hh.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::short_str_capacity().
str
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> const CharT* json::basic_string_key< CharT, Traits, Allocator >::str private
Pointer to the array of characters.
Definition at line 227 of file string_key.hh.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::basic_string_key(), json::basic_string_key< CharT, Traits, Allocator >::copy_other(), json::basic_string_key< CharT, Traits, Allocator >::data(), json::basic_string_key< CharT, Traits, Allocator >::is_short_str(), json::basic_string_key< CharT, Traits, Allocator >::make_empty(), json::basic_string_key< CharT, Traits, Allocator >::mutable_str(), json::string_key_literals::operator"" _sk(), and json::string_key_literals::operator"" _ss().
str_size
template<typename CharT, typename Traits = std::char_traits<CharT>, typename Allocator = json::allocator<CharT>> size_type json::basic_string_key< CharT, Traits, Allocator >::str_size private
Size of the string.
Definition at line 226 of file string_key.hh.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::basic_string_key(), json::basic_string_key< CharT, Traits, Allocator >::copy_other(), json::basic_string_key< CharT, Traits, Allocator >::make_empty(), and json::basic_string_key< CharT, Traits, Allocator >::size().
The documentation for this class was generated from the following files:
string_key.hh
string_key.inl