Json: json::parser::impl Namespace Reference
json::parser::impl Namespace Reference
Classes
struct is_token
struct is_token< token< CharForwardIterator > >
Functions
token_type determine_token_type (char starting_char)
Determines the token type of a piece of source code from its first character.
bool is_number (char c)
True if a character represents a numeric value.
bool is_whitespace (char c)
True if a character represents a whitespace.
bool is_structural (char c)
True if a character represents one of the six structural characters in json.
bool is_delimiter (char c)
True if a character represents a delimiter character. A delimiter character is any of the valid characters after a number or keyword literal.
json::string code_point_to_utf8 (unsigned code_point)
Converts a unicode code-point to UTF-8.
template<typename CharForwardIterator >
size_t comment_length (CharForwardIterator begin)
Returns the length of a comment token in the source.
template<typename CharForwardIterator >
size_t string_length (CharForwardIterator begin)
Returns the length of a string token in the source.
template<typename CharForwardIterator >
size_t number_length (CharForwardIterator begin)
template<typename CharForwardIterator >
size_t keyword_length (CharForwardIterator begin)
Returns the length in characters of a keyword token. The only keywords in json are true, false and null.
template<typename CharForwardIterator >
size_t token_length (CharForwardIterator begin, token_type type)
Returns the length of a token in the source given the position of the token and its type.
template<typename TokenForwardIterator >
TokenForwardIterator skip_comments (TokenForwardIterator begin, TokenForwardIterator end)
Advances begin until it's not pointing to a comment or until it reaches end.
template<typename TokenForwardIterator >
json::value parse_object (TokenForwardIterator begin, TokenForwardIterator end, TokenForwardIterator &new_begin)
Interprets the sequence of tokens [begin, end) as an object and returns it.
template<typename TokenForwardIterator >
size_t count_array_elements (TokenForwardIterator begin, TokenForwardIterator end)
Counts the number of elements an array will have by inspecting its tokens so that memory for those elements can be allocated beforehand.
template<typename TokenForwardIterator >
json::value parse_array (TokenForwardIterator begin, TokenForwardIterator end, TokenForwardIterator &new_begin)
Interprets the sequence of tokens [begin, end) as an array and returns it.
template<typename CharForwardIterator >
json::value parse_string (const token< CharForwardIterator > &t)
Constructs a string from a token that represents a string in the source.
template<typename CharForwardIterator >
bool represents_floating_point (CharForwardIterator begin, CharForwardIterator end)
True if the string represents a floating point number.
template<typename CharForwardIterator >
int string_to_int (CharForwardIterator begin, CharForwardIterator end)
Converts the range of characters [begin, end) representing an integral number to the value it represents.
template<typename CharForwardIterator >
double string_to_double (CharForwardIterator begin, CharForwardIterator end)
Converts the range of characters [begin, end) representing a real number to the value it represents.
template<typename CharForwardIterator >
json::value parse_number (const token< CharForwardIterator > &t)
Constructs a numeric value form a token that represents a number in the source.
template<typename CharForwardIterator >
json::value parse_boolean (const token< CharForwardIterator > &t)
Constructs a boolean value form a token that represents a boolean in the source.
Function Documentation
code_point_to_utf8()
JSON_API json::string json::parser::impl::code_point_to_utf8 (unsigned code_point)
Converts a unicode code-point to UTF-8.
Definition at line 82 of file parser.cc.
Referenced by parse_string(), and json::parser::syntax_error::syntax_error().
       {
         json::string result;
         // Based on description from http://en.wikipedia.org/wiki/UTF-8
         if (code_point <= 0x7f)
         {
           result.resize(1);
           result[0] = static_cast<char>(code_point);
         }
         else if (code_point <= 0x7FF)
         {
           result.resize(2);
           result[1] = static_cast<char>(0x80 | (0x3f & code_point));
           result[0] = static_cast<char>(0xC0 | (0x1f & (code_point >> 6)));
         }
         else if (code_point <= 0xFFFF)
         {
           result.resize(3);
           result[2] = static_cast<char>(0x80 | (0x3f & code_point));
           result[1] = static_cast<char>(0x80 | (0x3f & (code_point >> 6)));
           result[0] = static_cast<char>(0xE0 | (0xf & (code_point >> 12)));
         }
         else if (code_point <= 0x10FFFF)
         {
           result.resize(4);
           result[3] = static_cast<char>(0x80 | (0x3f & code_point));
           result[2] = static_cast<char>(0x80 | (0x3f & (code_point >> 6)));
           result[1] = static_cast<char>(0x80 | (0x3f & (code_point >> 12)));
           result[0] = static_cast<char>(0xF0 | (0x7 & (code_point >> 18)));
         }
         return result;
       }
comment_length()
template<typename CharForwardIterator > size_t json::parser::impl::comment_length (CharForwardIterator begin)
Returns the length of a comment token in the source.
Definition at line 10 of file parser.inl.
References json::parser::string.
Referenced by json::parser::syntax_error::syntax_error(), and token_length().
       {
         auto end = std::next(begin);
         // Check if we're dealing with a c comment or a c++ comment
         if (*end == '/')
         {
           while (*end != '\n' && *end != '\0')
             ++end;
           return std::distance(begin, end);
         }
         else if (*end == '*')
         {
           while (*end != '\0' && (*end != '*' || *std::next(end) != '/'))
             ++end;
           if (*end == '\0')
             throw syntax_error{ "Unclosed c style comment." };
           return std::distance(begin, end) + 2; // +2 to account the ending "*/". In the c++ comments we don't
                               // add 1 because the newline is not part of the comment
         }
         else
         {
           throw syntax_error{ ("Unexpected character following '/'. Expected '/' or '*', found '" + std::string{ *std::next(end) } +"' instead.").c_str() };
         }
       }
count_array_elements()
template<typename TokenForwardIterator > size_t json::parser::impl::count_array_elements (TokenForwardIterator begin, TokenForwardIterator end)
Counts the number of elements an array will have by inspecting its tokens so that memory for those elements can be allocated beforehand.
Definition at line 294 of file parser.inl.
References json::parser::close_curly_brace, json::parser::close_square_bracket, json::parser::comma, json::parser::open_curly_brace, and json::parser::open_square_bracket.
Referenced by parse_array(), and json::parser::syntax_error::syntax_error().
       {
         size_t square_bracket_level = 1;
         size_t curly_brace_level = 0;
         size_t commas = 0;
         while (begin != end)
         {
           switch (begin->type)
           {
           case token_type::open_square_bracket:
             ++square_bracket_level;
             break;
           case token_type::close_square_bracket:
             --square_bracket_level;
             break;
           case token_type::open_curly_brace:
             ++curly_brace_level;
             break;
           case token_type::close_curly_brace:
             --curly_brace_level;
             break;
           // Add an element to the array for every comma at the scope of the array
           case token_type::comma:
             if (square_bracket_level == 1 && curly_brace_level == 0)
               ++commas;
             break;
           default:
             break;
           }
           // End of object. Closing ] found
           if (square_bracket_level == 0)
             break;
           ++begin;
         }
         return commas + 1; // +1 to account for the last object, which doesn't have a comma
       }
determine_token_type()
JSON_API token_type json::parser::impl::determine_token_type (char starting_char)
Determines the token type of a piece of source code from its first character.
Definition at line 13 of file parser.cc.
References json::parser::boolean, json::parser::close_curly_brace, json::parser::close_square_bracket, json::parser::colon, json::parser::comma, json::parser::comment, json::parser::null, json::parser::number, json::parser::open_curly_brace, json::parser::open_square_bracket, and json::parser::string.
Referenced by json::parser::syntax_error::syntax_error(), and json::parser::tokenize().
       {
         // Lookup table mapping each char with the token type that starts with that char
         static const std::pair<char, token_type> map[] = {
           { '"', token_type::string }, { ',', token_type::comma }, { '-', token_type::number },
           { '/', token_type::comment }, { '0', token_type::number }, { '1', token_type::number },
           { '2', token_type::number }, { '3', token_type::number }, { '4', token_type::number },
           { '5', token_type::number }, { '6', token_type::number }, { '7', token_type::number },
           { '8', token_type::number }, { '9', token_type::number }, { ':', token_type::colon },
           { '[', token_type::open_square_bracket }, { ']', token_type::close_square_bracket },
           { 'f', token_type::boolean }, { 'n', token_type::null }, { 't', token_type::boolean },
           { '{', token_type::open_curly_brace }, { '}', token_type::close_curly_brace }
         };
         const auto compare_keys = [](const std::pair<char, token_type> & a, char key)
         {
           return a.first < key;
         };
         // Look if there's a possible token type for the given char
         auto it = std::lower_bound(std::begin(map), std::end(map), starting_char, compare_keys);
         // If there is, return it
         if (it->first == starting_char)
           return it->second;
         // If not, there is a syntax error
         else
           throw syntax_error{ ("Character " + std::string{ starting_char } + " could not be recognized.").c_str() };
       }
is_delimiter()
JSON_API bool json::parser::impl::is_delimiter (char c)
True if a character represents a delimiter character. A delimiter character is any of the valid characters after a number or keyword literal.
Definition at line 62 of file parser.cc.
References is_structural(), and is_whitespace().
Referenced by keyword_length(), number_length(), and json::parser::syntax_error::syntax_error().
       {
         return is_whitespace(c) || is_structural(c) || c == '/' || c == '\0';
       }
is_number()
JSON_API bool json::parser::impl::is_number (char c)
True if a character represents a numeric value.
Definition at line 43 of file parser.cc.
Referenced by number_length(), and json::parser::syntax_error::syntax_error().
       {
         return c >= '0' && c <= '9';
       }
is_structural()
JSON_API bool json::parser::impl::is_structural (char c)
True if a character represents one of the six structural characters in json.
Definition at line 55 of file parser.cc.
Referenced by is_delimiter(), and json::parser::syntax_error::syntax_error().
       {
         return c == '{' || c == '}' || c == '[' || c == ']' || c == ':' || c == ',';
       }
is_whitespace()
JSON_API bool json::parser::impl::is_whitespace (char c)
True if a character represents a whitespace.
Definition at line 49 of file parser.cc.
Referenced by is_delimiter(), json::parser::syntax_error::syntax_error(), and json::parser::tokenize().
       {
         return c == '\t' || c == '\n' || c == '\r' || c == ' ';
       }
keyword_length()
template<typename CharForwardIterator > size_t json::parser::impl::keyword_length (CharForwardIterator begin)
Returns the length in characters of a keyword token. The only keywords in json are true, false and null.
Definition at line 88 of file parser.inl.
References is_delimiter().
Referenced by json::parser::syntax_error::syntax_error(), and token_length().
       {
         constexpr size_t length_of_true = 4;
         constexpr size_t length_of_false = 5;
         constexpr size_t length_of_null = 4;
         const char * const true_str = "true";
         const char * const false_str = "false";
         const char * const null_str = "null";
         if (*begin == 't')
         {
           const auto end = std::next(begin, length_of_true);
           if (std::equal(true_str, true_str + length_of_true, begin, end) && is_delimiter(*end))
             return length_of_true;
           else
             throw syntax_error{ "Unrecognized keyword." };
         }
         else if (*begin == 'f')
         {
           const auto end = std::next(begin, length_of_false);
           if (std::equal(false_str, false_str + length_of_false, begin, end) && is_delimiter(*end))
             return length_of_false;
           else
             throw syntax_error{ "Unrecognized keyword." };
         }
         const auto end = std::next(begin, length_of_null);
         if (std::equal(null_str, null_str + length_of_null, begin, end) && is_delimiter(*end))
           return length_of_null;
         else
           throw syntax_error{ "Unrecognized keyword." };
       }
number_length()
template<typename CharForwardIterator > size_t json::parser::impl::number_length (CharForwardIterator begin)
Definition at line 57 of file parser.inl.
References is_delimiter(), and is_number().
Referenced by json::parser::syntax_error::syntax_error(), and token_length().
       {
         auto end = std::next(begin);
         bool dot_read = false;
         bool exp_read = false;
         for (;; ++end)
         {
           if (is_number(*end))
             continue;
           else if (!dot_read && *end == '.')
             dot_read = true;
           else if (!exp_read && (*end == 'e' || *end == 'E'))
           {
             exp_read = true;
             // Account for unary plus and minus in the exponent
             if (*std::next(end) == '+' || *std::next(end) == '-')
               ++end;
           }
           else if (is_delimiter(*end))
             break;
           else
             throw syntax_error{ "Unknown character found when parsing number literal." };
         }
         return std::distance(begin, end);
       }
parse_array()
template<typename TokenForwardIterator > json::value json::parser::impl::parse_array (TokenForwardIterator begin, TokenForwardIterator end, TokenForwardIterator & new_begin)
Interprets the sequence of tokens [begin, end) as an array and returns it.
Definition at line 336 of file parser.inl.
References json::array, json::parser::build_value(), json::parser::close_square_bracket, json::parser::comma, count_array_elements(), and skip_comments().
Referenced by json::parser::build_value(), and json::parser::syntax_error::syntax_error().
       {
         json::value root{ value_type::array };
         json::array & array = root.as_array();
         // Increment begin to skip the '[' token
         ++begin;
         // Check for bad input
         begin = skip_comments(begin, end);
         if (begin == end)
           throw syntax_error{ "Too few tokens when parsing array" };
         // Check for empty array
         if (begin->type == token_type::close_square_bracket)
         {
           new_begin = std::next(begin, 1);
           return root;
         }
         // Determine from the tokens the amount of elements in the array and preallocate the memory for them
         array.reserve(count_array_elements(begin, end));
         for (;;)
         {
           // Skip comments before the value
           begin = skip_comments(begin, end);
           // Parse the value
           array.push_back(build_value(begin, end, begin));
           // Comments after the value
           begin = skip_comments(begin, end);
           // Bad input
           if (begin == end)
             throw syntax_error{ "Too few tokens when parsing array" };
           // Comma
           else if (begin->type == token_type::comma)
             ++begin;
           // Last element of the array. Closing ']'
           else if (begin->type == token_type::close_square_bracket)
           {
             ++begin;
             break;
           }
           // Bad input
           else
             throw syntax_error{ "End ] for array not found" };
         }
         new_begin = begin;
         return root;
       }
parse_boolean()
template<typename CharForwardIterator > json::value json::parser::impl::parse_boolean (const token< CharForwardIterator > & t)
Constructs a boolean value form a token that represents a boolean in the source.
Definition at line 511 of file parser.inl.
References json::parser::token< CharForwardIterator >::begin.
Referenced by json::parser::build_value(), and json::parser::syntax_error::syntax_error().
       {
         // The string [begin, end) can only be "true" or "false", bad input was discarded
         // in tokenization step, so checking the first letter is enough
         return bool{ *t.begin == 't' };
       }
parse_number()
template<typename CharForwardIterator > json::value json::parser::impl::parse_number (const token< CharForwardIterator > & t)
Constructs a numeric value form a token that represents a number in the source.
Definition at line 501 of file parser.inl.
References json::parser::token< CharForwardIterator >::begin, json::parser::token< CharForwardIterator >::end, represents_floating_point(), string_to_double(), and string_to_int().
Referenced by json::parser::build_value(), and json::parser::syntax_error::syntax_error().
       {
         if (represents_floating_point(t.begin, t.end))
           return string_to_double(t.begin, t.end);
         else
           return string_to_int(t.begin, t.end);
       }
parse_object()
template<typename TokenForwardIterator > json::value json::parser::impl::parse_object (TokenForwardIterator begin, TokenForwardIterator end, TokenForwardIterator & new_begin)
Interprets the sequence of tokens [begin, end) as an object and returns it.
Definition at line 217 of file parser.inl.
References json::value::as_string(), json::parser::build_value(), json::parser::close_curly_brace, json::parser::colon, json::parser::comma, json::object, skip_comments(), and json::parser::string.
Referenced by json::parser::build_value(), and json::parser::syntax_error::syntax_error().
       {
         json::value root{ value_type::object };
         // Increment begin to skip the '{' token
         ++begin;
         // Check for comments and bad input
         begin = skip_comments(begin, end);
         if (begin == end)
           throw syntax_error{ "Too few tokens when parsing object" };
         // Check for empty object
         if (begin->type == token_type::close_curly_brace)
         {
           new_begin = std::next(begin, 1);
           return root;
         }
         for (;;)
         {
           // Structure of a member: string - colon - value - comma or }
           // Skip possible comments
           begin = skip_comments(begin, end);
           if (begin->type != token_type::string)
             throw syntax_error{ "Non string value as member key for object." };
           // Read the key
           json::string key = build_value(begin, end, begin).as_string();
           // Assert the next token is a colon
           begin = skip_comments(begin, end);
           if (begin == end || begin->type != token_type::colon)
             throw syntax_error{ "Expected : after member key when parsing object." };
           // Skip the : as it contains no valuable information. We only need to assert it's there
           ++begin;
           begin = skip_comments(begin, end);
           if (begin == end)
             throw syntax_error{ "Expected value after : when parsing object." };
           // Read the data of the member
           json::value member = build_value(begin, end, begin);
           // Try to insert new value
           if (root.as_object().insert(std::move(key), std::move(member)) == root.as_object().end())
             throw syntax_error{ ("Repeated member key \"" + key + "\" when parsing object").c_str() };
           // Comments
           begin = skip_comments(begin, end);
           // Bad input
           if (begin == end)
             throw syntax_error{ "Too few tokens when parsing array" };
           // Comma
           else if (begin->type == token_type::comma)
             ++begin;
           // Last element of the array. Closing '}'
           else if (begin->type == token_type::close_curly_brace)
           {
             ++begin;
             break;
           }
           // Bad input
           else
             throw syntax_error{ "End } for array not found" };
         }
         new_begin = begin;
         return root;
       }
parse_string()
template<typename CharForwardIterator > json::value json::parser::impl::parse_string (const token< CharForwardIterator > & t)
Constructs a string from a token that represents a string in the source.
Definition at line 392 of file parser.inl.
References json::parser::token< CharForwardIterator >::begin, code_point_to_utf8(), json::parser::token< CharForwardIterator >::end, and json::parser::string.
Referenced by json::parser::build_value(), and json::parser::syntax_error::syntax_error().
       {
         // Remove the first and last characters as the "" are not part of the string
         json::string str{ std::next(t.begin), t.end };
         str.pop_back(); // Use pop_back instead std::prev(t.end) in order to allow forward iterators
         // Scan for '\\' to look for control characters
         for (auto it = str.begin(); it != str.end(); ++it)
         {
           if (*it == '\\')
           {
             // Avoid dereferencing the end iterator
             const char next = it + 1 == str.end() ? '\0' : it[1];
             switch (next)
             {
               // For " and \ just erase the control character \ before
               case '"':
               case '\\':
               {
                 it = str.erase(it);
                 break;
               }
               case 'b':
               {
                 it = str.erase(it);
                 *it = '\b';
                 break;
               }
               case 'f':
               {
                 it = str.erase(it);
                 *it = '\f';
                 break;
               }
               case 'n':
               {
                 it = str.erase(it);
                 *it = '\n';
                 break;
               }
               case 'r':
               {
                 it = str.erase(it);
                 *it = '\r';
                 break;
               }
               case 't':
               {
                 it = str.erase(it);
                 *it = '\t';
                 break;
               }
               case 'u':
               {
                 const unsigned code_point = static_cast<unsigned>(std::stoi(std::string{ it + 1, it + 5 }, nullptr, 16));
                 it = str.erase(it, it + 5);
                 const auto code_point_in_utf8 = code_point_to_utf8(code_point);
                 it = str.insert(it, code_point_in_utf8.begin(), code_point_in_utf8.end());
                 break;
               }
               default:
               {
                 throw syntax_error{ "Invalid control character" };
               }
             }
           }
         }
         return std::move(str);
       }
represents_floating_point()
template<typename CharForwardIterator > bool json::parser::impl::represents_floating_point (CharForwardIterator begin, CharForwardIterator end)
True if the string represents a floating point number.
Definition at line 465 of file parser.inl.
Referenced by parse_number(), and json::parser::syntax_error::syntax_error().
       {
         // A string represents a floating point if it has a fraction part '.' or a exponent ('e' or 'E')
         return
           std::find(begin, end, '.') != end ||
           std::find(begin, end, 'e') != end ||
           std::find(begin, end, 'E') != end;
       }
skip_comments()
template<typename TokenForwardIterator > TokenForwardIterator json::parser::impl::skip_comments (TokenForwardIterator begin, TokenForwardIterator end)
Advances begin until it's not pointing to a comment or until it reaches end.
Definition at line 207 of file parser.inl.
References json::parser::comment.
Referenced by json::parser::build_value(), json::parser::parse(), parse_array(), parse_object(), and json::parser::syntax_error::syntax_error().
       {
         while (begin != end && begin->type == token_type::comment)
           ++begin;
         return begin;
       }
string_length()
template<typename CharForwardIterator > size_t json::parser::impl::string_length (CharForwardIterator begin)
Returns the length of a string token in the source.
Definition at line 40 of file parser.inl.
Referenced by json::parser::syntax_error::syntax_error(), and token_length().
       {
         auto end = begin;
         // Json considers \" a control character representing " inside the string, so don't end the string if we find \"
         while (*std::next(end) != '\0' && !(*std::next(end) == '"' && !(*end == '\\')))
           ++end;
         ++end;
         if (*end == '\0')
           throw syntax_error{ "Unclosed string." };
         return std::distance(begin, end) + 1; // +1  because the ending " is part of the string
       }
string_to_double()
template<typename CharForwardIterator > double json::parser::impl::string_to_double (CharForwardIterator begin, CharForwardIterator end)
Converts the range of characters [begin, end) representing a real number to the value it represents.
Definition at line 489 of file parser.inl.
Referenced by parse_number(), and json::parser::syntax_error::syntax_error().
       {
         constexpr ptrdiff_t buffer_size = 64;
         assert(std::distance(begin, end) < buffer_size);
         char buffer[buffer_size] = { 0 };
         std::copy(begin, end, buffer);
         return atof(buffer);
       }
string_to_int()
template<typename CharForwardIterator > int json::parser::impl::string_to_int (CharForwardIterator begin, CharForwardIterator end)
Converts the range of characters [begin, end) representing an integral number to the value it represents.
Definition at line 476 of file parser.inl.
Referenced by parse_number(), and json::parser::syntax_error::syntax_error().
       {
         // Using ptrdiff_t instead of size_t to avoid signed/unsigned mismatch warning on the comparison of the assertion
         constexpr ptrdiff_t buffer_size = 32;
         assert(std::distance(begin, end) < buffer_size);
         char buffer[buffer_size] = { 0 };
         std::copy(begin, end, buffer);
         return atoi(buffer);
       }
token_length()
template<typename CharForwardIterator > size_t json::parser::impl::token_length (CharForwardIterator begin, token_type type)
Returns the length of a token in the source given the position of the token and its type.
Definition at line 122 of file parser.inl.
References json::parser::boolean, json::parser::close_curly_brace, json::parser::close_square_bracket, json::parser::colon, json::parser::comma, json::parser::comment, comment_length(), keyword_length(), json::parser::null, json::parser::number, number_length(), json::parser::open_curly_brace, json::parser::open_square_bracket, json::parser::string, and string_length().
Referenced by json::parser::syntax_error::syntax_error(), and json::parser::tokenize().
       {
         switch (type)
         {
           case token_type::open_curly_brace:
           case token_type::close_curly_brace:
           case token_type::open_square_bracket:
           case token_type::close_square_bracket:
           case token_type::colon:
           case token_type::comma:
           {
             // Structural character tokens have a single character
             return 1;
           }
           case token_type::comment:
           {
             return comment_length(begin);
           }
           case token_type::string:
           {
             return string_length(begin);
           }
           case token_type::number:
           {
             return number_length(begin);
           }
           case token_type::boolean:
           case token_type::null:
           {
             return keyword_length(begin);
           }
           default:
           {
             // Control should never reach here
             assert(false);
             return 0;
           }
         }
       }