Json: json::parser Namespace Reference
json::parser Namespace Reference
Namespaces
impl
Classes
class syntax_error
Exception class thrown by tokenize and build_value when encountering bad input.
struct token
A token is every individual piece of information within a json source file.
Enumerations
enum token_type {
token_type::open_curly_brace, token_type::close_curly_brace, token_type::open_square_bracket, token_type::close_square_bracket,
token_type::colon, token_type::comma, token_type::comment, token_type::string,
token_type::number, token_type::boolean, token_type::null
}
Possible token types a json source file may have.
Functions
json::vector< token< const char * > > tokenize (const char *source)
Parses the whole string until a null character is found Same as tokenize(source, source + strlen(source))
json::vector< token< const char * > > tokenize (const json::string &source)
Parses the string [source.begin(), source.end()) Same as tokenize(source.c_str(), source.c_str() + source.size())
json::value parse (const char *source)
Same as parse(source, source + strlen(source))
json::value parse (const json::string &source)
Same as parse(source.c_str(), source.c_str() + source.size())
json::value parse (std::istream &is)
Reads the whole stream, then parses that.
template<typename CharForwardIterator >
json::vector< token< CharForwardIterator > > tokenize (CharForwardIterator begin, CharForwardIterator end)
Parses the range of characters [begin, end) in json format into a sequence of lexical tokens. Tokens will contain pointers to the source range so it's important for it to live while the tokens are being used CharForwardIterator must satisfy ForwardIterator CharForwardIterator::value_type must be char.
JSON_API json::vector< token< const char * > > tokenize (const json::string &&source)=delete
Tokens hold references to the source string so tokenizing a temporary string is explicitly forbidden.
template<typename TokenForwardIterator >
json::value build_value (TokenForwardIterator begin, TokenForwardIterator end)
Builds a value from a sequence of tokens represented by the range [begin, end) TokenForwardIterator must satisfy ForwardIterator TokenForwardIterator::value_type must be token<T>
template<typename TokenForwardIterator >
json::value build_value (TokenForwardIterator begin, TokenForwardIterator end, TokenForwardIterator &new_begin)
Builds a value from a sequence of tokens represented by the range [begin, end) The last parameter outputs the position of the iterator, in case the whole range isn't used.
template<typename CharForwardIterator >
json::value parse (CharForwardIterator begin, CharForwardIterator end)
Parses the string [begin, end) in json format into a value containing the data represented in the string.
Enumeration Type Documentation
token_type
enum json::parser::token_type strong
Possible token types a json source file may have.
Enumerator
open_curly_brace
close_curly_brace
open_square_bracket
close_square_bracket
colon
comma
comment
string
number
boolean
null
Definition at line 16 of file parser.hh.
     {
       open_curly_brace,
       close_curly_brace,
       open_square_bracket,
       close_square_bracket,
       colon,
       comma,
       comment,
       string,
       number,
       boolean,
       null
     };
Function Documentation
build_value() [1/2]
template<typename TokenForwardIterator > json::value json::parser::build_value (TokenForwardIterator begin, TokenForwardIterator end)
Builds a value from a sequence of tokens represented by the range [begin, end) TokenForwardIterator must satisfy ForwardIterator TokenForwardIterator::value_type must be token<T>
Definition at line 529 of file parser.inl.
Referenced by parse(), json::parser::impl::parse_array(), json::parser::impl::parse_object(), and json::parser::syntax_error::syntax_error().
     {
       TokenForwardIterator dummy;
       return build_value(begin, end, dummy);
     }
build_value() [2/2]
template<typename TokenForwardIterator > json::value json::parser::build_value (TokenForwardIterator begin, TokenForwardIterator end, TokenForwardIterator & new_begin)
Builds a value from a sequence of tokens represented by the range [begin, end) The last parameter outputs the position of the iterator, in case the whole range isn't used.
Definition at line 536 of file parser.inl.
References boolean, null, number, open_curly_brace, open_square_bracket, json::parser::impl::parse_array(), json::parser::impl::parse_boolean(), json::parser::impl::parse_number(), json::parser::impl::parse_object(), json::parser::impl::parse_string(), json::parser::impl::skip_comments(), and string.
     {
       // Assert that TokenIterator dereferences to a token
       static_assert(
         impl::is_token<typename
           std::iterator_traits<TokenForwardIterator>::value_type>::value,
         "In function build_value TokenForwardIterator must dereference to json::parser::token");
       using namespace ::json::parser::impl;
       begin = skip_comments(begin, end);
       if (begin == end)
         throw syntax_error{ "Error at parsing empty string" };
       switch (begin->type)
       {
         case token_type::open_curly_brace:
         {
           return parse_object(begin, end, new_begin);
         }
         case token_type::open_square_bracket:
         {
           return parse_array(begin, end, new_begin);
         }
         case token_type::string:
         {
           new_begin = std::next(begin, 1);
           return parse_string(*begin);
         }
         case token_type::number:
         {
           new_begin = std::next(begin, 1);
           return parse_number(*begin);
         }
         case token_type::boolean:
         {
           new_begin = std::next(begin, 1);
           return parse_boolean(*begin);
         }
         case token_type::null:
         {
           new_begin = std::next(begin, 1);
           return json::value{};
         }
         default:
           throw syntax_error{ "Invalid token type at the beginning of a value." };
       }
     }
parse() [1/4]
template<typename CharForwardIterator > json::value json::parser::parse (CharForwardIterator begin, CharForwardIterator end)
Parses the string [begin, end) in json format into a value containing the data represented in the string.
Definition at line 587 of file parser.inl.
References build_value(), json::parser::impl::skip_comments(), and tokenize().
     {
       const auto tokens = tokenize(begin, end);
       typename std::vector<token<CharForwardIterator>>::const_iterator tokens_end;
       json::value root = build_value(tokens.begin(), tokens.end(), tokens_end);
       // A json file may have comments after the value
       tokens_end = impl::skip_comments(tokens_end, tokens.end());
       // This will assert the file only contains a single value
       if (tokens_end != tokens.end())
         throw syntax_error{ "More than one value in the string" };
       return root;
     }
parse() [2/4]
JSON_API json::value json::parser::parse (const char * source)
Same as parse(source, source + strlen(source))
Definition at line 120 of file parser.cc.
Referenced by operator>>(), parse(), and json::parser::syntax_error::syntax_error().
     {
       return parse(source, source + std::strlen(source));
     }
parse() [3/4]
JSON_API json::value json::parser::parse (const json::string & source)
Same as parse(source.c_str(), source.c_str() + source.size())
Definition at line 125 of file parser.cc.
References parse().
     {
       return parse(source.c_str(), source.c_str() + source.size());
     }
parse() [4/4]
JSON_API json::value json::parser::parse (std::istream & is)
Reads the whole stream, then parses that.
Definition at line 130 of file parser.cc.
References parse().
     {
       std::basic_ostringstream<char, std::char_traits<char>, json::allocator<char>> oss;
       oss << is.rdbuf();
       return parse(oss.str());
     }
tokenize() [1/4]
template<typename CharForwardIterator > json::vector< token< CharForwardIterator > > json::parser::tokenize (CharForwardIterator begin, CharForwardIterator end)
Parses the range of characters [begin, end) in json format into a sequence of lexical tokens. Tokens will contain pointers to the source range so it's important for it to live while the tokens are being used CharForwardIterator must satisfy ForwardIterator CharForwardIterator::value_type must be char.
Definition at line 165 of file parser.inl.
References json::parser::impl::determine_token_type(), json::parser::impl::is_whitespace(), and json::parser::impl::token_length().
     {
       static_assert(std::is_same<typename
         std::iterator_traits<CharForwardIterator>::value_type,
         char>::value,
         "In function tokenize CharForwardIterator must dereference to char");
       using namespace ::json::parser::impl;
       json::vector<token<CharForwardIterator>> tokens;
       // Pre allocate some memory to avoid frequent reallocations. The starting size is temptative,
       // and the function may reallocate depending on data quality, but it should very rarely need
       // more than two allocations.
       constexpr size_t average_token_to_char_ratio = 6; // This was decided by running tests on a set of data
       const size_t source_length = std::distance(begin, end);
       tokens.reserve(source_length / average_token_to_char_ratio);
       while (begin != end)
       {
         const char & c = *begin;
         // Skip whitespace
         if (is_whitespace(c))
           ++begin;
         else
         {
           const token_type type = determine_token_type(c);
           const size_t length = token_length(begin, type);
           const auto token_end = std::next(begin, length);
           tokens.push_back({ type, begin, token_end });
           begin = token_end;
         }
       }
       return tokens;
     }
tokenize() [2/4]
JSON_API json::vector<token<const char *> > json::parser::tokenize (const json::string && source) delete
Tokens hold references to the source string so tokenizing a temporary string is explicitly forbidden.
tokenize() [3/4]
JSON_API json::vector< token< const char * > > json::parser::tokenize (const char * source)
Parses the whole string until a null character is found Same as tokenize(source, source + strlen(source))
Definition at line 69 of file parser.cc.
Referenced by parse(), json::parser::syntax_error::syntax_error(), and tokenize().
     {
       return tokenize(source, source + std::strlen(source));
     }
tokenize() [4/4]
JSON_API json::vector< token< const char * > > json::parser::tokenize (const json::string & source)
Parses the string [source.begin(), source.end()) Same as tokenize(source.c_str(), source.c_str() + source.size())
Definition at line 74 of file parser.cc.
References tokenize().
     {
       return tokenize(source.c_str(), source.c_str() + source.size());
     }