Json: value.hh File Reference
value.hh File Reference
#include "config.hh"
#include "string_key.hh"
#include "mpl/variant.hh"
#include <stdexcept>
#include <cstdint>
#include "value.inl"
Classes
class json::invalid_operation
Thrown when trying to access a value as a type different to its own (eg: using as_int on an array type) or when comparing for inequality two values of different types.
class json::object
Data structure representing json object. An object is an unordered set of name/value pairs. An object begins with { (left brace) and ends with } (right brace). Each name is followed by : (colon) and the name/value pairs are separated by , (comma). http://www.json.org/.
class json::value
Data structure representing a json value http://www.json.org.
Namespaces
json
Typedefs
using json::array = json::vector< json::value >
Data structure representing a json array. An array is an ordered collection of values. An array begins with [ (left bracket) and ends with ] (right bracket). Values are separated by , (comma). http://www.json.org/.
Enumerations
enum json::value_type {
json::value_type::null = 0, json::value_type::integer = 1, json::value_type::real = 2, json::value_type::boolean = 3,
json::value_type::string = 4, json::value_type::array = 5, json::value_type::object = 6
}
Enum with the possible types a json::value may hold.
Functions
template<>
JSON_API void std::swap (json::value &a, json::value &b)
Specialization of std::swap for json::value.
Function Documentation
swap()
template<> JSON_API void std::swap (json::value & a, json::value & b)
Specialization of std::swap for json::value.
Definition at line 843 of file value.cc.
References json::value::swap(), and std::swap().
Referenced by std::swap().
   {
     a.swap(b);
   }