Json: json::parser::syntax_error Class Reference
json::parser::syntax_error Class Reference
Exception class thrown by tokenize and build_value when encountering bad input.
#include <parser.hh>
Public Member Functions
syntax_error (const char *msg)
Detailed Description
Exception class thrown by tokenize and build_value when encountering bad input.
Definition at line 41 of file parser.hh.
Constructor & Destructor Documentation
syntax_error()
json::parser::syntax_error::syntax_error (const char * msg) inline
Definition at line 44 of file parser.hh.
References json::parser::build_value(), json::parser::impl::code_point_to_utf8(), json::parser::impl::comment_length(), json::parser::impl::count_array_elements(), json::parser::impl::determine_token_type(), json::parser::impl::is_delimiter(), json::parser::impl::is_number(), json::parser::impl::is_structural(), json::parser::impl::is_whitespace(), JSON_API, json::parser::impl::keyword_length(), json::parser::impl::number_length(), operator>>(), json::parser::parse(), json::parser::impl::parse_array(), json::parser::impl::parse_boolean(), json::parser::impl::parse_number(), json::parser::impl::parse_object(), json::parser::impl::parse_string(), json::parser::impl::represents_floating_point(), json::parser::impl::skip_comments(), json::parser::impl::string_length(), json::parser::impl::string_to_double(), json::parser::impl::string_to_int(), json::parser::impl::token_length(), and json::parser::tokenize().
         : runtime_error{ msg }
       {}
The documentation for this class was generated from the following file:
parser.hh