Json: json::object Class Reference
json::object Class Reference
Data structure representing json object. An object is an unordered set of name/value pairs. An object begins with { (left brace) and ends with } (right brace). Each name is followed by : (colon) and the name/value pairs are separated by , (comma). http://www.json.org/.
#include <value.hh>
Public Types
using map_type = json::map< json::string_key, json::value >
using value_type = map_type::value_type
using mapped_type = map_type::mapped_type
using key_type = map_type::key_type
using reference = map_type::reference
using const_reference = map_type::const_reference
using pointer = map_type::pointer
using const_pointer = map_type::const_pointer
using size_type = map_type::size_type
using difference_type = map_type::difference_type
using key_compare = map_type::key_compare
using allocator_type = map_type::allocator_type
using iterator = map_type::iterator
using const_iterator = map_type::const_iterator
using reverse_iterator = map_type::reverse_iterator
using const_reverse_iterator = map_type::const_reverse_iterator
Public Member Functions
object ()=default
Constructs an empty object.
object (const map_type &map)
Constructs an object from a map of strings to json::values.
object (map_type &&map) noexcept(std::is_nothrow_move_constructible< map_type >::value)
Constructs an object from a map of strings to json::values by move. map becomes empty.
size_t size () const noexcept
Number of members.
bool empty () const noexcept
True if size == 0.
void clear ()
Removes all members.
iterator begin () noexcept
Returns an iterator to the first member.
iterator end () noexcept
Returns an iterator to one past the last member.
const_iterator begin () const noexcept
Returns a const iterator (read only) to the first member.
const_iterator end () const noexcept
Returns a const iterator(read only) to one past the last member.
const_iterator cbegin () const noexcept
Returns a const iterator (read only) to the first member.
const_iterator cend () const noexcept
Returns a const iterator (read only) to the first member.
reverse_iterator rbegin () noexcept
Returns a reverse iterator to the last member. Incrementing the iterator will advance to the previous member.
reverse_iterator rend () noexcept
Returns a reverse iterator to one before the first member.
const_reverse_iterator rbegin () const noexcept
Returns a const reverse iterator (read only) to the last member.
const_reverse_iterator rend () const noexcept
Returns a const reverse iterator (read_only) to one before the first member.
const_reverse_iterator crbegin () const noexcept
Returns a const reverse iterator (read only) to the last member.
const_reverse_iterator crend () const noexcept
Returns a const reverse iterator (read_only) to one before the first member.
bool operator== (const object &other) const
True if each member compares equal to each member of other.
bool operator!= (const object &other) const
True if not equal.
bool operator< (const object &other) const
Lexicographically compares each member with each member of the other object.
bool operator<= (const object &other) const
Lexicographically compares each member with each member of the other object.
bool operator> (const object &other) const
Lexicographically compares each member with each member of the other object.
bool operator>= (const object &other) const
Lexicographically compares each member with each member of the other object.
value & operator[] (const char *key)
Accesses a member with the given key. Inserts a new default constructed element if not found.
value & operator[] (const json::string &key)
Accesses a member with the given key. Inserts a new default constructed element if not found.
value & operator[] (json::string &&key)
Accesses a member with the given key. Inserts a new default constructed element if not found. If a new element is inserted, the key will be constructed by moving, so the parameter string will become empty.
value & operator[] (static_string key)
Accesses a member with the given key. Inserts a new default constructed element if not found If a value is inserted, the string used as key will not be copied. The map will keep a reference to the original string.
const value & operator[] (const char *key) const noexcept
Accesses a member with the given key. Returns null reference if not found.
const value & operator[] (const json::string &key) const noexcept
Accesses a member with the given key. Returns null reference if not found.
value & at (const char *key)
Accesses a member with the given key. Throws std::out_of_range if not found.
value & at (const json::string &key)
Accesses a member with the given key. Throws std::out_of_range if not found.
const value & at (const char *key) const
Accesses a member with the given key. Throws std::out_of_range if not found.
const value & at (const json::string &key) const
Accesses a member with the given key. Throws std::out_of_range if not found.
iterator find (const char *key) noexcept
Accesses a member with the given key. Returns end iterator if not found.
iterator find (const json::string &key) noexcept
Accesses a member with the given key. Returns end iterator if not found.
const_iterator find (const char *key) const noexcept
Accesses a member with the given key. Returns end iterator if not found.
const_iterator find (const json::string &key) const noexcept
Accesses a member with the given key. Returns end iterator if not found.
bool is_member (const char *key) const noexcept
True if there exists a member with the given key.
bool is_member (const json::string &key) const noexcept
True if there exists a member with the given key.
bool remove_member (const char *key)
Removes a member with the given key.
bool remove_member (const json::string &key)
Removes a member with the given key.
json::vector< json::string > member_names () const
Returns a vector with the keys of all members.
json::vector< const char * > member_names_as_c_str () const
Returns a vector with the keys of all members. The vector doesn't own the strings, so the pointers will invalidate if the member gets removed or the object gets destroyed.
iterator insert (json::string_key key, const json::value &val)
Inserts an element with the given key. Returns an iterator to the inserted element, or end on failure.
iterator insert (json::string_key key, json::value &&val)
Inserts an element with the given key. Returns an iterator to the inserted element, or end on failure.
template<typename ... Args>
iterator emplace (json::string_key key, Args &&... args)
Inserts an element with the given key and constructs it in place from variadic arguments. Returns an iterator to the inserted element, or end on failure.
Private Attributes
map_type members
Detailed Description
Data structure representing json object. An object is an unordered set of name/value pairs. An object begins with { (left brace) and ends with } (right brace). Each name is followed by : (colon) and the name/value pairs are separated by , (comma). http://www.json.org/.
Definition at line 44 of file value.hh.
Member Typedef Documentation
allocator_type
using json::object::allocator_type = map_type::allocator_type
Definition at line 60 of file value.hh.
const_iterator
using json::object::const_iterator = map_type::const_iterator
Definition at line 63 of file value.hh.
const_pointer
using json::object::const_pointer = map_type::const_pointer
Definition at line 55 of file value.hh.
const_reference
using json::object::const_reference = map_type::const_reference
Definition at line 53 of file value.hh.
const_reverse_iterator
using json::object::const_reverse_iterator = map_type::const_reverse_iterator
Definition at line 65 of file value.hh.
difference_type
using json::object::difference_type = map_type::difference_type
Definition at line 58 of file value.hh.
iterator
using json::object::iterator = map_type::iterator
Definition at line 62 of file value.hh.
key_compare
using json::object::key_compare = map_type::key_compare
Definition at line 59 of file value.hh.
key_type
using json::object::key_type = map_type::key_type
Definition at line 51 of file value.hh.
map_type
using json::object::map_type = json::map<json::string_key, json::value>
Definition at line 47 of file value.hh.
mapped_type
using json::object::mapped_type = map_type::mapped_type
Definition at line 50 of file value.hh.
pointer
using json::object::pointer = map_type::pointer
Definition at line 54 of file value.hh.
reference
using json::object::reference = map_type::reference
Definition at line 52 of file value.hh.
reverse_iterator
using json::object::reverse_iterator = map_type::reverse_iterator
Definition at line 64 of file value.hh.
size_type
using json::object::size_type = map_type::size_type
Definition at line 57 of file value.hh.
value_type
using json::object::value_type = map_type::value_type
Definition at line 49 of file value.hh.
Constructor & Destructor Documentation
object() [1/3]
json::object::object () default
Constructs an empty object.
object() [2/3]
json::object::object (const map_type & map)
Constructs an object from a map of strings to json::values.
Definition at line 531 of file value.cc.
     : members(map)
   {}
object() [3/3]
json::object::object (map_type && map) noexcept
Constructs an object from a map of strings to json::values by move. map becomes empty.
Definition at line 535 of file value.cc.
     : members(std::move(map))
   {}
Member Function Documentation
at() [1/4]
value & json::object::at (const char * key)
Accesses a member with the given key. Throws std::out_of_range if not found.
Definition at line 713 of file value.cc.
References members, and json::string.
Referenced by at().
   {
     // Search for the given key
     const auto it = members.find(key);
     // If found return the value
     if (it != members.end())
       return it->second;
     // Otherwise throw out of range
     else
       throw std::out_of_range{ std::string("Member \"") + key + "\" not found in object" };
   }
at() [2/4]
value& json::object::at (const json::string & key)
Accesses a member with the given key. Throws std::out_of_range if not found.
at() [3/4]
const value & json::object::at (const char * key) const
Accesses a member with the given key. Throws std::out_of_range if not found.
Definition at line 730 of file value.cc.
References at(), members, and json::string.
   {
     // Search for the given key
     const auto it = members.find(key);
     // If found return the value
     if (it != members.end())
       return it->second;
     // Otherwise throw out of range
     else
       throw std::out_of_range{ std::string("Member \"") + key + "\" not found in object" };
   }
at() [4/4]
const value& json::object::at (const json::string & key) const
Accesses a member with the given key. Throws std::out_of_range if not found.
begin() [1/2]
object::iterator json::object::begin () noexcept
Returns an iterator to the first member.
Definition at line 554 of file value.cc.
References members.
Referenced by json::writer::write_object().
   {
     return members.begin();
   }
begin() [2/2]
object::const_iterator json::object::begin () const noexcept
Returns a const iterator (read only) to the first member.
Definition at line 564 of file value.cc.
References cbegin().
   {
     return cbegin();
   }
cbegin()
object::const_iterator json::object::cbegin () const noexcept
Returns a const iterator (read only) to the first member.
Definition at line 574 of file value.cc.
References members.
Referenced by begin().
   {
     return members.cbegin();
   }
cend()
object::const_iterator json::object::cend () const noexcept
Returns a const iterator (read only) to the first member.
Definition at line 579 of file value.cc.
References members.
Referenced by end().
   {
     return members.cend();
   }
clear()
void json::object::clear ()
Removes all members.
Definition at line 549 of file value.cc.
References members.
   {
     members.clear();
   }
crbegin()
object::const_reverse_iterator json::object::crbegin () const noexcept
Returns a const reverse iterator (read only) to the last member.
Definition at line 604 of file value.cc.
References members.
Referenced by rbegin().
   {
     return members.crbegin();
   }
crend()
object::const_reverse_iterator json::object::crend () const noexcept
Returns a const reverse iterator (read_only) to one before the first member.
Definition at line 609 of file value.cc.
References members.
Referenced by rend().
   {
     return members.crend();
   }
emplace()
template<typename ... Args> object::iterator json::object::emplace (json::string_key key, Args &&... args)
Inserts an element with the given key and constructs it in place from variadic arguments. Returns an iterator to the inserted element, or end on failure.
Definition at line 5 of file value.inl.
References members.
   {
     const auto it_success = members.emplace(
       std::piecewise_construct,
       std::forward_as_tuple(std::move(key)),
       std::forward_as_tuple(std::forward<Args>(args)...));
     if (it_success.second)
       return { it_success.first };
     else
       return members.end();
   }
empty()
bool json::object::empty () const noexcept
True if size == 0.
Definition at line 544 of file value.cc.
References members.
Referenced by json::writer::write_object().
   {
     return members.empty();
   }
end() [1/2]
object::iterator json::object::end () noexcept
Returns an iterator to one past the last member.
Definition at line 559 of file value.cc.
References members.
Referenced by json::writer::write_object().
   {
     return members.end();
   }
end() [2/2]
object::const_iterator json::object::end () const noexcept
Returns a const iterator(read only) to one past the last member.
Definition at line 569 of file value.cc.
References cend().
   {
     return cend();
   }
find() [1/4]
object::iterator json::object::find (const char * key) noexcept
Accesses a member with the given key. Returns end iterator if not found.
Definition at line 747 of file value.cc.
References members, and json::string.
Referenced by find().
   {
     return members.find(key);
   }
find() [2/4]
iterator json::object::find (const json::string & key) noexcept
Accesses a member with the given key. Returns end iterator if not found.
find() [3/4]
object::const_iterator json::object::find (const char * key) const noexcept
Accesses a member with the given key. Returns end iterator if not found.
Definition at line 757 of file value.cc.
References find(), members, and json::string.
   {
     return members.find(key);
   }
find() [4/4]
const_iterator json::object::find (const json::string & key) const noexcept
Accesses a member with the given key. Returns end iterator if not found.
insert() [1/2]
object::iterator json::object::insert (json::string_key key, const json::value & val)
Inserts an element with the given key. Returns an iterator to the inserted element, or end on failure.
Definition at line 819 of file value.cc.
References members.
   {
     const auto it_success = members.emplace(std::move(key), val);
     if (it_success.second)
       return { it_success.first };
     else
       return { members.end() };
   }
insert() [2/2]
object::iterator json::object::insert (json::string_key key, json::value && val)
Inserts an element with the given key. Returns an iterator to the inserted element, or end on failure.
Definition at line 828 of file value.cc.
References members.
   {
     const auto it_success = members.emplace(std::move(key), std::move(val));
     if (it_success.second)
       return { it_success.first };
     else
       return { members.end() };
   }
is_member() [1/2]
bool json::object::is_member (const char * key) const noexcept
True if there exists a member with the given key.
Definition at line 767 of file value.cc.
References members, and json::string.
   {
     return members.find(key) != members.end();
   }
is_member() [2/2]
bool json::object::is_member (const json::string & key) const noexcept
True if there exists a member with the given key.
member_names()
json::vector< json::string > json::object::member_names () const
Returns a vector with the keys of all members.
Definition at line 797 of file value.cc.
References members.
   {
     json::vector<json::string> names;
     names.reserve(members.size());
     for (const auto & pair : members)
       names.push_back(json::string{ pair.first });
     return names;
   }
member_names_as_c_str()
json::vector< const char * > json::object::member_names_as_c_str () const
Returns a vector with the keys of all members. The vector doesn't own the strings, so the pointers will invalidate if the member gets removed or the object gets destroyed.
Definition at line 808 of file value.cc.
References members.
   {
     json::vector<const char *> names;
     names.reserve(members.size());
     for (const auto & pair : members)
       names.push_back(pair.first.c_str());
     return names;
   }
operator!=()
bool json::object::operator!= (const object & other) const
True if not equal.
Definition at line 619 of file value.cc.
References members.
   {
     return members != other.members;
   }
operator<()
bool json::object::operator< (const object & other) const
Lexicographically compares each member with each member of the other object.
Definition at line 624 of file value.cc.
References members.
   {
     return members < other.members;
   }
operator<=()
bool json::object::operator<= (const object & other) const
Lexicographically compares each member with each member of the other object.
Definition at line 629 of file value.cc.
References members.
   {
     return members <= other.members;
   }
operator==()
bool json::object::operator== (const object & other) const
True if each member compares equal to each member of other.
Definition at line 614 of file value.cc.
References members.
   {
     return members == other.members;
   }
operator>()
bool json::object::operator> (const object & other) const
Lexicographically compares each member with each member of the other object.
Definition at line 634 of file value.cc.
References members.
   {
     return members > other.members;
   }
operator>=()
bool json::object::operator>= (const object & other) const
Lexicographically compares each member with each member of the other object.
Definition at line 639 of file value.cc.
References members.
   {
     return members >= other.members;
   }
operator[]() [1/6]
value & json::object::operator[] (const char * key)
Accesses a member with the given key. Inserts a new default constructed element if not found.
Definition at line 648 of file value.cc.
References members.
   {
     // Search for the given key
     const auto it = members.find(key);
     // If found return the value
     if (it != members.end())
       return it->second;
     // Otherwise insert a new value and return it
     else
       return members.emplace(key, json::value{}).first->second;
   }
operator[]() [2/6]
value & json::object::operator[] (const json::string & key)
Accesses a member with the given key. Inserts a new default constructed element if not found.
Definition at line 660 of file value.cc.
References members.
   {
     // Search for the given key
     const auto it = members.find(key);
     // If found return the value
     if (it != members.end())
       return it->second;
     // Otherwise insert a new value and return it
     else
       return members.emplace(key, json::value{}).first->second;
   }
operator[]() [3/6]
value & json::object::operator[] (json::string && key)
Accesses a member with the given key. Inserts a new default constructed element if not found. If a new element is inserted, the key will be constructed by moving, so the parameter string will become empty.
Definition at line 672 of file value.cc.
References members.
   {
     // Search for the given key
     const auto it = members.find(key);
     // If found return the value
     if (it != members.end())
       return it->second;
     // Otherwise insert a new value and return it
     else
       return members.emplace(std::move(key), json::value{}).first->second;
   }
operator[]() [4/6]
value & json::object::operator[] (static_string key)
Accesses a member with the given key. Inserts a new default constructed element if not found If a value is inserted, the string used as key will not be copied. The map will keep a reference to the original string.
Definition at line 684 of file value.cc.
References json::basic_static_string< CharT, Traits >::c_str(), and members.
   {
     // Search for the given key
     const auto it = members.find(key.c_str());
     // If found return the value
     if (it != members.end())
       return it->second;
     // Otherwise insert a new value and return it
     else
       return members.emplace(key, json::value{}).first->second;
   }
operator[]() [5/6]
const value & json::object::operator[] (const char * key) const noexcept
Accesses a member with the given key. Returns null reference if not found.
Definition at line 696 of file value.cc.
References members, and json::value::null.
   {
     // Search for the given key
     const auto it = members.find(key);
     // If found return the value
     if (it != members.end())
       return it->second;
     // Otherwise return null
     else
       return json::value::null;
   }
operator[]() [6/6]
const value & json::object::operator[] (const json::string & key) const noexcept
Accesses a member with the given key. Returns null reference if not found.
Definition at line 708 of file value.cc.
   {
     return (*this)[key.c_str()];
   }
rbegin() [1/2]
object::reverse_iterator json::object::rbegin () noexcept
Returns a reverse iterator to the last member. Incrementing the iterator will advance to the previous member.
Definition at line 584 of file value.cc.
References members.
   {
     return members.rbegin();
   }
rbegin() [2/2]
object::const_reverse_iterator json::object::rbegin () const noexcept
Returns a const reverse iterator (read only) to the last member.
Definition at line 594 of file value.cc.
References crbegin().
   {
     return crbegin();
   }
remove_member() [1/2]
bool json::object::remove_member (const char * key)
Removes a member with the given key.
Definition at line 777 of file value.cc.
References members, and json::string.
   {
     // map::erase(iterator) has constant time complexity, so erase(find(key)) is equivalent in complexity
     // to erase(key), with the extra advantage of find being aware of transparent comparison
     const auto it = members.find(key);
     if (it != members.end())
     {
       members.erase(it);
       return true;
     }
     else
       return false;
   }
remove_member() [2/2]
bool json::object::remove_member (const json::string & key)
Removes a member with the given key.
rend() [1/2]
object::reverse_iterator json::object::rend () noexcept
Returns a reverse iterator to one before the first member.
Definition at line 589 of file value.cc.
References members.
   {
     return members.rend();
   }
rend() [2/2]
object::const_reverse_iterator json::object::rend () const noexcept
Returns a const reverse iterator (read_only) to one before the first member.
Definition at line 599 of file value.cc.
References crend().
   {
     return crend();
   }
size()
size_t json::object::size () const noexcept
Number of members.
Definition at line 539 of file value.cc.
References members.
   {
     return members.size();
   }
Member Data Documentation
members
map_type json::object::members private
Definition at line 184 of file value.hh.
Referenced by at(), begin(), cbegin(), cend(), clear(), crbegin(), crend(), emplace(), empty(), end(), find(), insert(), is_member(), member_names(), member_names_as_c_str(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), operator[](), rbegin(), remove_member(), rend(), and size().
The documentation for this class was generated from the following files:
value.hh
value.cc
value.inl