Json: json::mpl::variant< Ts > Class Template Reference
json::mpl::variant< Ts > Class Template Reference
#include <variant.hh>
Public Types
using value_types = mpl::type_list< Ts... >
List of types of the variant.
Public Member Functions
variant () noexcept=default
Default constructor constructs an invalid variant.
~variant ()
Destructor calls the destructor on the internally managed object, if any.
template<typename T , typename ... Args>
variant (mpl::type_list< T >, Args &&... args)
Constructs in place an object of type T.
template<typename T >
variant (T &&val)
Copy or move constructs an object of type T.
template<typename T >
variant & operator= (T &&val)
Copy or move assigns an object of type T.
variant (const variant &other)
Copy constructor from a variant of the same type.
variant (variant &&other)
Move constructor from a variant of the same type.
variant & operator= (const variant &other)
Copy assignment from a variant of the same type.
variant & operator= (variant &&other)
Move assignment from a variant of the same type.
template<typename T , typename ... Args>
void emplace (Args &&... args)
Constructs in place an object of type T.
void destroy ()
Destroys the internally managed object and sets the variant to invalid.
template<typename T >
T & as ()
Accesses the internal object if it's of type T. Throws std::bad_cast otherwise.
template<typename T >
const T & as () const
Accesses the internal object if it's of type T. Throws std::bad_cast otherwise.
template<typename T >
bool is () const noexcept
True if T is the type of the internal object, false otherwise.
size_t index () const noexcept
Returns the index of the type of the internal object in the list value_types or npos if not valid.
bool valid () const noexcept
True if there's a managed object.
template<typename T >
variant< Ts... > & operator= (T &&val)
Static Public Attributes
static constexpr size_t npos = static_cast<size_t>(-1)
Index of an invalid variant.
Private Attributes
size_t vtable_index = npos
char buffer [buffer_size] = { 0 }
Index of the current type.
Static Private Attributes
static constexpr size_t buffer_size = mpl::biggest_size<value_types>::value
static const copy_control_traits_base * vtables [mpl::size< value_types >::value]
Array with the virtual tables of the types of the variant.
Detailed Description
template<typename ... Ts>
class json::mpl::variant< Ts >
Definition at line 14 of file variant.hh.
Member Typedef Documentation
value_types
template<typename ... Ts> using json::mpl::variant< Ts >::value_types = mpl::type_list<Ts...>
List of types of the variant.
Definition at line 18 of file variant.hh.
Constructor & Destructor Documentation
variant() [1/5]
template<typename ... Ts> json::mpl::variant< Ts >::variant () default noexcept
Default constructor constructs an invalid variant.
~variant()
template<typename ... Ts> json::mpl::variant< Ts >::~variant ()
Destructor calls the destructor on the internally managed object, if any.
Definition at line 12 of file variant.inl.
     {
       destroy();
     }
variant() [2/5]
template<typename ... Ts> template<typename T , typename ... Args> json::mpl::variant< Ts >::variant (mpl::type_list< T > , Args &&... args)
Constructs in place an object of type T.
Definition at line 19 of file variant.inl.
     {
       emplace<T>(std::forward<Args>(args)...);
     }
variant() [3/5]
template<typename ... Ts> template<typename T > json::mpl::variant< Ts >::variant (T && val)
Copy or move constructs an object of type T.
Definition at line 26 of file variant.inl.
     {
       // Decay in order to remove cv qualifiers and references
       emplace<typename std::decay<T>::type>(std::forward<T>(val));
     }
variant() [4/5]
template<typename ... Ts> json::mpl::variant< Ts >::variant (const variant< Ts > & other)
Copy constructor from a variant of the same type.
Definition at line 53 of file variant.inl.
       : vtable_index(other.vtable_index)
     {
       if (valid())
         vtables[vtable_index]->copy_construct(buffer, other.buffer);
     }
variant() [5/5]
template<typename ... Ts> json::mpl::variant< Ts >::variant (variant< Ts > && other)
Move constructor from a variant of the same type.
Definition at line 61 of file variant.inl.
       : vtable_index(other.vtable_index)
     {
       other.vtable_index = npos;
       if (valid())
         vtables[vtable_index]->move_construct(buffer, other.buffer);
     }
Member Function Documentation
as() [1/2]
template<typename ... Ts> template<typename T > T & json::mpl::variant< Ts >::as ()
Accesses the internal object if it's of type T. Throws std::bad_cast otherwise.
Definition at line 131 of file variant.inl.
Referenced by json::value::as_array(), json::value::as_bool(), json::value::as_c_string(), json::value::as_double(), json::value::as_float(), json::value::as_int(), json::value::as_int64(), json::value::as_object(), json::value::as_string(), json::value::as_uint(), json::value::as_uint64(), json::value::operator<(), json::value::operator==(), json::value::stored_bool(), json::value::stored_double(), and json::value::stored_int().
     {
       static_assert(contains<T, value_types>::value, "Invalid type for function as of variant");
       // Check if the type of this variant is the requested type
       if (vtables[vtable_index] == &copy_control_traits<T>::global_instance)
         return reinterpret_cast<T &>(buffer);
       else
         throw std::bad_cast{};
     }
as() [2/2]
template<typename ... Ts> template<typename T > const T & json::mpl::variant< Ts >::as () const
Accesses the internal object if it's of type T. Throws std::bad_cast otherwise.
Definition at line 144 of file variant.inl.
     {
       static_assert(contains<T, value_types>::value, "Invalid type for function as of variant");
       // Check if the type of this variant is the requested type
       if (vtables[vtable_index] == &copy_control_traits<T>::global_instance)
         return reinterpret_cast<const T &>(buffer);
       else
         throw std::bad_cast{};
     }
destroy()
template<typename ... Ts> void json::mpl::variant< Ts >::destroy ()
Destroys the internally managed object and sets the variant to invalid.
Definition at line 120 of file variant.inl.
Referenced by json::mpl::variant< int64_t, double, bool, json::string, json::array, json::object >::destroy().
     {
       if (valid())
       {
         vtables[vtable_index]->destroy(buffer);
         vtable_index = npos;
       }
     }
emplace()
template<typename ... Ts> template<typename T , typename ... Args> void json::mpl::variant< Ts >::emplace (Args &&... args)
Constructs in place an object of type T.
Definition at line 110 of file variant.inl.
Referenced by json::value::value().
     {
       static_assert(contains<T, value_types>::value, "Invalid type for function emplace of variant");
       destroy();
       vtable_index = find<T, value_types>::value;
       ::new (buffer) T(std::forward<Args>(args)...);
     }
index()
template<typename ... Ts> size_t json::mpl::variant< Ts >::index () const noexcept
Returns the index of the type of the internal object in the list value_types or npos if not valid.
Definition at line 165 of file variant.inl.
Referenced by json::value::type().
     {
       return vtable_index;
     }
is()
template<typename ... Ts> template<typename T > bool json::mpl::variant< Ts >::is () const noexcept
True if T is the type of the internal object, false otherwise.
Definition at line 157 of file variant.inl.
Referenced by json::value::is_array(), json::value::is_bool(), json::value::is_int(), json::value::is_object(), json::value::is_real(), and json::value::is_string().
     {
       static_assert(contains<T, value_types>::value, "Invalid type for function is of variant");
       return vtable_index == mpl::find<T, value_types>::value;
     }
operator=() [1/4]
template<typename ... Ts> template<typename T > variant<Ts...>& json::mpl::variant< Ts >::operator= (T && val)
Definition at line 34 of file variant.inl.
     {
       // Decay in order to remove cv qualifiers and references
       using actual_type = typename std::decay<T>::type;
       try
       {
         // If the type of the managed object is the type of the assigned object, use the assignment operator
         this->as<actual_type>() = std::forward<T>(val);
       }
       catch (const std::bad_cast &)
       {
         // Otherwise emplace
         emplace<typename std::decay<T>::type>(std::forward<T>(val));
       }
       return *this;
     }
operator=() [2/4]
template<typename ... Ts> template<typename T > variant& json::mpl::variant< Ts >::operator= (T && val)
Copy or move assigns an object of type T.
operator=() [3/4]
template<typename ... Ts> variant< Ts... > & json::mpl::variant< Ts >::operator= (const variant< Ts > & other)
Copy assignment from a variant of the same type.
Definition at line 70 of file variant.inl.
     {
       if (vtable_index == other.vtable_index)
       {
         if (valid())
           vtables[vtable_index]->copy_assign(buffer, other.buffer);
       }
       else
       {
         destroy();
         vtable_index = other.vtable_index;
         if (valid())
           vtables[vtable_index]->copy_construct(buffer, other.buffer);
       }
       return *this;
     }
operator=() [4/4]
template<typename ... Ts> variant< Ts... > & json::mpl::variant< Ts >::operator= (variant< Ts > && other)
Move assignment from a variant of the same type.
Definition at line 89 of file variant.inl.
     {
       if (vtable_index == other.vtable_index)
       {
         if (valid())
           vtables[vtable_index]->move_assign(buffer, other.buffer);
       }
       else
       {
         destroy();
         vtable_index = other.vtable_index;
         if (valid())
           vtables[vtable_index]->move_construct(buffer, other.buffer);
       }
       other.vtable_index = npos;
       return *this;
     }
valid()
template<typename ... Ts> bool json::mpl::variant< Ts >::valid () const noexcept
True if there's a managed object.
Definition at line 171 of file variant.inl.
Referenced by json::value::is_null().
     {
       return vtable_index != npos;
     }
Member Data Documentation
buffer
template<typename ... Ts> char json::mpl::variant< Ts >::buffer[buffer_size] = { 0 } private
Index of the current type.
Definition at line 82 of file variant.hh.
Referenced by json::mpl::variant< int64_t, double, bool, json::string, json::array, json::object >::operator=(), and json::mpl::variant< int64_t, double, bool, json::string, json::array, json::object >::variant().
buffer_size
template<typename ... Ts> constexpr size_t json::mpl::variant< Ts >::buffer_size = mpl::biggest_size<value_types>::value static private
Definition at line 77 of file variant.hh.
npos
template<typename ... Ts> constexpr size_t json::mpl::variant< Ts >::npos = static_cast<size_t>(-1) static
Index of an invalid variant.
Definition at line 22 of file variant.hh.
vtable_index
template<typename ... Ts> size_t json::mpl::variant< Ts >::vtable_index = npos private
Definition at line 81 of file variant.hh.
Referenced by json::mpl::variant< int64_t, double, bool, json::string, json::array, json::object >::operator=().
vtables
template<typename ... Ts> const copy_control_traits_base * json::mpl::variant< Ts >::vtables static private
Initial value:
= {
      &copy_control_traits<Ts>::global_instance...
    }
Array with the virtual tables of the types of the variant.
Definition at line 79 of file variant.hh.
The documentation for this class was generated from the following files:
variant.hh
variant.inl