Json: json::value Class Reference
json::value Class Reference
Data structure representing a json value http://www.json.org.
#include <value.hh>
Public Member Functions
value ()
Default constructor constructs a null value.
value (int v) noexcept
Constructs an integer value with the value of v.
value (unsigned v) noexcept
Constructs an integer value with the value of v.
value (int64_t v) noexcept
Constructs an integer value with the value of v.
value (uint64_t v) noexcept
Constructs an integer value with the value of v.
value (float v) noexcept
Constructs a real value with the value of v.
value (double v) noexcept
Constructs a real value with the value of v.
value (bool v) noexcept
Constructs a boolean value with the value of v.
value (const char *v)
Constructs a string value with the value of v.
value (const json::string &v)
Constructs a string value with the value of v.
value (json::string &&v)
Constructs a string value by move. v becomes empty.
value (const json::array &v)
Constructs an array value with the value of v.
value (json::array &&v)
Constructs an array value by move. v becomes empty.
value (const json::object &v)
Constructs an object value with the value of v.
value (json::object &&v)
Constructs an object value by move. v becomes empty.
value (std::initializer_list< json::value > list)
Constructs an array value from an initializer list of json values.
value (std::initializer_list< std::pair< const json::string_key, json::value >> list)
Constructs an object value from an initializer list of pairs of string-value.
value (value_type type)
Constructs an empty value of the given type.
value & operator= (int v) noexcept
Convert the value to integer, then assigns v.
value & operator= (unsigned v) noexcept
Convert the value to integer, then assigns v.
value & operator= (int64_t v) noexcept
Convert the value to integer, then assigns v.
value & operator= (uint64_t v) noexcept
Convert the value to integer, then assigns v.
value & operator= (float v) noexcept
Convert the value to real, then assigns v.
value & operator= (double v) noexcept
Convert the value to real, then assigns v.
value & operator= (bool v) noexcept
Convert the value to boolean, then assigns v.
value & operator= (const char *v)
Convert the value to string, then assigns v.
value & operator= (const json::string &v)
Convert the value to string, then assigns v.
value & operator= (json::string &&v)
Convert the value to string, then move assigns v. v becomes empty.
value & operator= (const json::array &v)
Convert the value to array, then assigns v.
value & operator= (json::array &&v)
Convert the value to array, then move assigns v. v becomes empty.
value & operator= (const json::object &v)
Convert the value to object, then assigns v.
value & operator= (json::object &&v)
Convert the value to object, then move assigns v. v becomes empty.
void swap (value &other) noexcept
Swaps the content of two values.
bool operator< (const value &other) const
True if both are the same type and this is less than other. Invalid operation if different type.
bool operator<= (const value &other) const
True if both are the same type and this is less than or equal to other. Invalid operation if different type.
bool operator>= (const value &other) const
True if both are the same type and this is greater than or equal to other. Invalid operation if different type.
bool operator> (const value &other) const
True if both are the same type and this is greater than other. Invalid operation if different type.
bool operator== (const value &other) const noexcept
True if both are the same type and values compare equal. False otherwise.
bool operator!= (const value &other) const noexcept
True if both are of different types or if their values don't compare equal.
int as_int () const
If numeric, returns the value casted to int. Invalid operation otherwise.
unsigned as_uint () const
If numeric, returns the value casted to unsigned. Invalid operation otherwise.
int64_t as_int64 () const
If numeric, returns the value casted to int64_t. Invalid operation otherwise.
uint64_t as_uint64 () const
If numeric, returns the value casted to uint64_t. Invalid operation otherwise.
float as_float () const
If numeric, returns the value casted to float. Invalid operation otherwise.
double as_double () const
If numeric, returns the value casted to double. Invalid operation otherwise.
bool as_bool () const
If boolean, returns the value. Invalid operation otherwise.
const char * as_c_string () const
If string, returns a pointer to the stored character array. Invalid operation otherwise.
json::string & as_string ()
If string, returns a reference to the stored string. Invalid operation otherwise.
const json::string & as_string () const
If string, returns a reference to the stored string. Invalid operation otherwise.
json::array & as_array ()
If array, returns a reference to the stored array. Invalid operation otherwise.
const json::array & as_array () const
If array, returns a reference to the stored array. Invalid operation otherwise.
json::object & as_object ()
If object, returns a reference to the stored object. Invalid operation otherwise.
const json::object & as_object () const
If object, returns a reference to the stored object. Invalid operation otherwise.
int64_t & stored_int ()
If integer, returns a reference to the stored int64_t. Invalid operation otherwise.
const int64_t & stored_int () const
If integer, returns a reference to the stored int64_t. Invalid operation otherwise.
double & stored_double ()
If real, returns a reference to the stored double. Invalid operation otherwise.
const double & stored_double () const
If real, returns a reference to the stored double. Invalid operation otherwise.
bool & stored_bool ()
If boolean, returns a reference to the stored bool. Invalid operation otherwise.
const bool & stored_bool () const
If boolean, returns a reference to the stored bool. Invalid operation otherwise.
bool is_null () const noexcept
True if type is null.
bool operator! () const noexcept
True if type is null.
bool is_int () const noexcept
True if type is integer.
bool is_real () const noexcept
True if type is real.
bool is_numeric () const noexcept
True if type is int or real.
bool is_bool () const noexcept
True if type is boolean.
bool is_string () const noexcept
True if type is string.
bool is_array () const noexcept
True if type is array.
bool is_object () const noexcept
True if type is object.
json::value_type type () const noexcept
Returns the type of the value.
Static Public Attributes
static const value null
Constant null value returned by const subscript operator of object on failure.
Private Attributes
mpl::variant< int64_t, double, bool, json::string, json::array, json::object > stored_value
Variant with the possible value types the class may have.
Detailed Description
Data structure representing a json value http://www.json.org.
This class is a variant type which can represent any of the following:
64 bit signed integer (int64_t)
double precision floating point value (double)
boolean (bool)
UTF-8 string (json::string)
an ordered sequence of json::value (json::array)
an unordered set of string-value pairs (json::object)
null
Type of the value can be queried with type() function and is represented as a json::value_type enum
A value is of null type by default, and can be converted to other types with the assignment operator. Trying to access a value with a type different to its own will throw a json::invalid_operation exception.
Definition at line 202 of file value.hh.
Constructor & Destructor Documentation
value() [1/18]
json::value::value ()
Default constructor constructs a null value.
Definition at line 14 of file value.cc.
 {}
value() [2/18]
json::value::value (int v) noexcept
Constructs an integer value with the value of v.
Definition at line 16 of file value.cc.
     : stored_value{ mpl::type_list<int64_t>{}, static_cast<int64_t>(v) }
   {}
value() [3/18]
json::value::value (unsigned v) noexcept
Constructs an integer value with the value of v.
Definition at line 20 of file value.cc.
     : stored_value{ mpl::type_list<int64_t>{}, static_cast<int64_t>(v) }
   {}
value() [4/18]
json::value::value (int64_t v) noexcept
Constructs an integer value with the value of v.
Definition at line 24 of file value.cc.
     : stored_value{ v }
   {}
value() [5/18]
json::value::value (uint64_t v) noexcept
Constructs an integer value with the value of v.
Definition at line 28 of file value.cc.
     : stored_value{ mpl::type_list<int64_t>{}, static_cast<int64_t>(v) }
   {}
value() [6/18]
json::value::value (float v) noexcept
Constructs a real value with the value of v.
Definition at line 32 of file value.cc.
     : stored_value{ mpl::type_list<double>{}, static_cast<double>(v) }
   {}
value() [7/18]
json::value::value (double v) noexcept
Constructs a real value with the value of v.
Definition at line 36 of file value.cc.
     : stored_value{ v }
   {}
value() [8/18]
json::value::value (bool v) noexcept
Constructs a boolean value with the value of v.
Definition at line 40 of file value.cc.
     : stored_value{ v }
   {}
value() [9/18]
json::value::value (const char * v)
Constructs a string value with the value of v.
Definition at line 44 of file value.cc.
     : stored_value{ mpl::type_list<json::string>{}, v }
   {}
value() [10/18]
json::value::value (const json::string & v)
Constructs a string value with the value of v.
Definition at line 48 of file value.cc.
     : stored_value{ v }
   {}
value() [11/18]
json::value::value (json::string && v)
Constructs a string value by move. v becomes empty.
Definition at line 52 of file value.cc.
     : stored_value{ std::move(v) }
   {}
value() [12/18]
json::value::value (const json::array & v)
Constructs an array value with the value of v.
Definition at line 56 of file value.cc.
     : stored_value{ v }
   {}
value() [13/18]
json::value::value (json::array && v)
Constructs an array value by move. v becomes empty.
Definition at line 60 of file value.cc.
     : stored_value{ std::move(v) }
   {}
value() [14/18]
json::value::value (const json::object & v)
Constructs an object value with the value of v.
Definition at line 64 of file value.cc.
     : stored_value{ v }
   {}
value() [15/18]
json::value::value (json::object && v)
Constructs an object value by move. v becomes empty.
Definition at line 68 of file value.cc.
     : stored_value{ std::move(v) }
   {}
value() [16/18]
json::value::value (std::initializer_list< json::value > list)
Constructs an array value from an initializer list of json values.
Definition at line 72 of file value.cc.
     : stored_value{ mpl::type_list<json::array>{}, list }
   {}
value() [17/18]
json::value::value (std::initializer_list< std::pair< const json::string_key, json::value >> list)
Constructs an object value from an initializer list of pairs of string-value.
Definition at line 76 of file value.cc.
     : stored_value{ mpl::type_list<json::object>{}, list }
   {}
value() [18/18]
json::value::value (value_type type) explicit
Constructs an empty value of the given type.
null
integer = 0
real = 0.0
boolean = false
string = ""
empty array
empty object
Definition at line 80 of file value.cc.
References json::array, json::boolean, json::mpl::variant< Ts >::emplace(), json::integer, json::null, json::object, json::real, stored_value, and json::string.
   {
     switch (type)
     {
       case value_type::null:
       {
         break;
       }
       case value_type::integer:
       {
         *this = 0;
         break;
       }
       case value_type::real:
       {
         *this = 0.0;
         break;
       }
       case value_type::boolean:
       {
         *this = false;
         break;
       }
       case value_type::string:
       {
         *this = "";
         break;
       }
       case value_type::array:
       {
         stored_value.emplace<json::array>();
         break;
       }
       case value_type::object:
       {
         stored_value.emplace<json::object>();
         break;
       }
     }
   }
Member Function Documentation
as_array() [1/2]
json::array & json::value::as_array ()
If array, returns a reference to the stored array. Invalid operation otherwise.
Definition at line 377 of file value.cc.
References json::mpl::variant< Ts >::as(), is_array(), and stored_value.
Referenced by json::writer::write().
   {
     if (is_array())
       return stored_value.as<json::array>();
     else
       throw invalid_operation{ "Value not compatible with as_array" };
   }
as_array() [2/2]
const json::array & json::value::as_array () const
If array, returns a reference to the stored array. Invalid operation otherwise.
Definition at line 385 of file value.cc.
References json::mpl::variant< Ts >::as(), is_array(), and stored_value.
   {
     if (is_array())
       return stored_value.as<json::array>();
     else
       throw invalid_operation{ "Value not compatible with as_array" };
   }
as_bool()
bool json::value::as_bool () const
If boolean, returns the value. Invalid operation otherwise.
Definition at line 345 of file value.cc.
References json::mpl::variant< Ts >::as(), is_bool(), and stored_value.
Referenced by json::writer::write().
   {
     if (is_bool())
       return stored_value.as<bool>();
     else
       throw invalid_operation{ "Value not compatible with as_bool" };
   }
as_c_string()
const char * json::value::as_c_string () const
If string, returns a pointer to the stored character array. Invalid operation otherwise.
Definition at line 353 of file value.cc.
References json::mpl::variant< Ts >::as(), is_string(), and stored_value.
   {
     if (is_string())
       return stored_value.as<json::string>().c_str();
     else
       throw invalid_operation{ "Value not compatible with as_c_string" };
   }
as_double()
double json::value::as_double () const
If numeric, returns the value casted to double. Invalid operation otherwise.
Definition at line 334 of file value.cc.
References json::mpl::variant< Ts >::as(), is_int(), is_real(), and stored_value.
Referenced by operator<(), and json::writer::write().
   {
     if (is_real())
       return stored_value.as<double>();
     else if (is_int())
       return static_cast<double>(stored_value.as<int64_t>());
     else
       throw invalid_operation{ "Value not compatible with as_double" };
   }
as_float()
float json::value::as_float () const
If numeric, returns the value casted to float. Invalid operation otherwise.
Definition at line 324 of file value.cc.
References json::mpl::variant< Ts >::as(), is_int(), is_real(), and stored_value.
   {
     if (is_real())
       return static_cast<float>(stored_value.as<double>());
     else if (is_int())
       return static_cast<float>(stored_value.as<int64_t>());
     else
       throw invalid_operation{ "Value not compatible with as_double" };
   }
as_int()
int json::value::as_int () const
If numeric, returns the value casted to int. Invalid operation otherwise.
Definition at line 284 of file value.cc.
References json::mpl::variant< Ts >::as(), is_int(), is_real(), and stored_value.
   {
     if (is_int())
       return static_cast<int>(stored_value.as<int64_t>());
     else if (is_real())
       return static_cast<int>(stored_value.as<double>());
     else
       throw invalid_operation{ "Value not compatible with as_int" };
   }
as_int64()
int64_t json::value::as_int64 () const
If numeric, returns the value casted to int64_t. Invalid operation otherwise.
Definition at line 304 of file value.cc.
References json::mpl::variant< Ts >::as(), is_int(), is_real(), and stored_value.
Referenced by json::writer::write().
   {
     if (is_int())
       return stored_value.as<int64_t>();
     else if (is_real())
       return static_cast<int64_t>(stored_value.as<double>());
     else
       throw invalid_operation{ "Value not compatible with as_int64" };
   }
as_object() [1/2]
json::object & json::value::as_object ()
If object, returns a reference to the stored object. Invalid operation otherwise.
Definition at line 393 of file value.cc.
References json::mpl::variant< Ts >::as(), is_object(), and stored_value.
Referenced by json::writer::write().
   {
     if (is_object())
       return stored_value.as<json::object>();
     else
       throw invalid_operation{ "Value not compatible with as_object" };
   }
as_object() [2/2]
const json::object & json::value::as_object () const
If object, returns a reference to the stored object. Invalid operation otherwise.
Definition at line 401 of file value.cc.
References json::mpl::variant< Ts >::as(), is_object(), and stored_value.
   {
     if (is_object())
       return stored_value.as<json::object>();
     else
       throw invalid_operation{ "Value not compatible with as_object" };
   }
as_string() [1/2]
json::string & json::value::as_string ()
If string, returns a reference to the stored string. Invalid operation otherwise.
Definition at line 361 of file value.cc.
References json::mpl::variant< Ts >::as(), is_string(), and stored_value.
Referenced by json::parser::impl::parse_object(), and json::writer::write().
   {
     if (is_string())
       return stored_value.as<json::string>();
     else
       throw invalid_operation{ "Value not compatible with as_string" };
   }
as_string() [2/2]
const json::string & json::value::as_string () const
If string, returns a reference to the stored string. Invalid operation otherwise.
Definition at line 369 of file value.cc.
References json::mpl::variant< Ts >::as(), is_string(), and stored_value.
   {
     if (is_string())
       return stored_value.as<json::string>();
     else
       throw invalid_operation{ "Value not compatible with as_string" };
   }
as_uint()
unsigned json::value::as_uint () const
If numeric, returns the value casted to unsigned. Invalid operation otherwise.
Definition at line 294 of file value.cc.
References json::mpl::variant< Ts >::as(), is_int(), is_real(), and stored_value.
   {
     if (is_int())
       return static_cast<unsigned>(stored_value.as<int64_t>());
     else if (is_real())
       return static_cast<unsigned>(stored_value.as<double>());
     else
       throw invalid_operation{ "Value not compatible with as_uint" };
   }
as_uint64()
uint64_t json::value::as_uint64 () const
If numeric, returns the value casted to uint64_t. Invalid operation otherwise.
Definition at line 314 of file value.cc.
References json::mpl::variant< Ts >::as(), is_int(), is_real(), and stored_value.
   {
     if (is_int())
       return static_cast<uint64_t>(stored_value.as<int64_t>());
     else if (is_real())
       return static_cast<uint64_t>(stored_value.as<double>());
     else
       throw invalid_operation{ "Value not compatible with as_uint64" };
   }
is_array()
bool json::value::is_array () const noexcept
True if type is array.
Definition at line 495 of file value.cc.
References json::mpl::variant< Ts >::is(), and stored_value.
Referenced by as_array(), and operator<().
   {
     return stored_value.is<json::array>();
   }
is_bool()
bool json::value::is_bool () const noexcept
True if type is boolean.
Definition at line 485 of file value.cc.
References json::mpl::variant< Ts >::is(), and stored_value.
Referenced by as_bool(), and operator<().
   {
     return stored_value.is<bool>();
   }
is_int()
bool json::value::is_int () const noexcept
True if type is integer.
Definition at line 470 of file value.cc.
References json::mpl::variant< Ts >::is(), and stored_value.
Referenced by as_double(), as_float(), as_int(), as_int64(), as_uint(), as_uint64(), is_numeric(), and stored_int().
   {
     return stored_value.is<int64_t>();
   }
is_null()
bool json::value::is_null () const noexcept
True if type is null.
Definition at line 460 of file value.cc.
References stored_value, and json::mpl::variant< Ts >::valid().
Referenced by operator!().
   {
     return !stored_value.valid();
   }
is_numeric()
bool json::value::is_numeric () const noexcept
True if type is int or real.
Definition at line 480 of file value.cc.
References is_int(), and is_real().
Referenced by operator<().
   {
     return is_int() || is_real();
   }
is_object()
bool json::value::is_object () const noexcept
True if type is object.
Definition at line 500 of file value.cc.
References json::mpl::variant< Ts >::is(), and stored_value.
Referenced by as_object(), and operator<().
   {
     return stored_value.is<json::object>();
   }
is_real()
bool json::value::is_real () const noexcept
True if type is real.
Definition at line 475 of file value.cc.
References json::mpl::variant< Ts >::is(), and stored_value.
Referenced by as_double(), as_float(), as_int(), as_int64(), as_uint(), as_uint64(), is_numeric(), stored_bool(), and stored_double().
   {
     return stored_value.is<double>();
   }
is_string()
bool json::value::is_string () const noexcept
True if type is string.
Definition at line 490 of file value.cc.
References json::mpl::variant< Ts >::is(), and stored_value.
Referenced by as_c_string(), as_string(), and operator<().
   {
     return stored_value.is<json::string>();
   }
operator!()
bool json::value::operator! () const noexcept
True if type is null.
Definition at line 465 of file value.cc.
References is_null().
   {
     return is_null();
   }
operator!=()
bool json::value::operator!= (const value & other) const noexcept
True if both are of different types or if their values don't compare equal.
Definition at line 276 of file value.cc.
   {
     return !(*this == other);
   }
operator<()
bool json::value::operator< (const value & other) const
True if both are the same type and this is less than other. Invalid operation if different type.
Definition at line 218 of file value.cc.
References json::mpl::variant< Ts >::as(), as_double(), is_array(), is_bool(), is_numeric(), is_object(), is_string(), and stored_value.
   {
     if (is_numeric() && other.is_numeric())
       return as_double() < other.as_double();
     else if (is_bool() && other.is_bool())
       return stored_value.as<bool>() < other.stored_value.as<bool>();
     else if (is_string() && other.is_string())
       return stored_value.as<json::string>() < other.stored_value.as<json::string>();
     else if (is_array() && other.is_array())
       return stored_value.as<json::array>() < other.stored_value.as<json::array>();
     else if (is_object() && other.is_object())
       return stored_value.as<json::object>() < other.stored_value.as<json::object>();
     else
       throw invalid_operation{ "Value not compatible with operator <" };
   }
operator<=()
bool json::value::operator<= (const value & other) const
True if both are the same type and this is less than or equal to other. Invalid operation if different type.
Definition at line 234 of file value.cc.
   {
     return *this < other || *this == other;
   }
operator=() [1/14]
value & json::value::operator= (int v) noexcept
Convert the value to integer, then assigns v.
Definition at line 124 of file value.cc.
References stored_value.
   {
     stored_value = static_cast<int64_t>(v);
     return *this;
   }
operator=() [2/14]
value & json::value::operator= (unsigned v) noexcept
Convert the value to integer, then assigns v.
Definition at line 130 of file value.cc.
References stored_value.
   {
     stored_value = static_cast<int64_t>(v);
     return *this;
   }
operator=() [3/14]
value & json::value::operator= (int64_t v) noexcept
Convert the value to integer, then assigns v.
Definition at line 136 of file value.cc.
References stored_value.
   {
     stored_value = v;
     return *this;
   }
operator=() [4/14]
value & json::value::operator= (uint64_t v) noexcept
Convert the value to integer, then assigns v.
Definition at line 142 of file value.cc.
References stored_value.
   {
     stored_value = static_cast<int64_t>(v);
     return *this;
   }
operator=() [5/14]
value & json::value::operator= (float v) noexcept
Convert the value to real, then assigns v.
Definition at line 148 of file value.cc.
References stored_value.
   {
     stored_value = static_cast<double>(v);
     return *this;
   }
operator=() [6/14]
value & json::value::operator= (double v) noexcept
Convert the value to real, then assigns v.
Definition at line 154 of file value.cc.
References stored_value.
   {
     stored_value = v;
     return *this;
   }
operator=() [7/14]
value & json::value::operator= (bool v) noexcept
Convert the value to boolean, then assigns v.
Definition at line 160 of file value.cc.
References stored_value.
   {
     stored_value = v;
     return *this;
   }
operator=() [8/14]
value & json::value::operator= (const char * v)
Convert the value to string, then assigns v.
Definition at line 166 of file value.cc.
References stored_value.
   {
     stored_value = json::string{ v };
     return *this;
   }
operator=() [9/14]
value & json::value::operator= (const json::string & v)
Convert the value to string, then assigns v.
Definition at line 172 of file value.cc.
References stored_value.
   {
     stored_value = v;
     return *this;
   }
operator=() [10/14]
value & json::value::operator= (json::string && v)
Convert the value to string, then move assigns v. v becomes empty.
Definition at line 178 of file value.cc.
References stored_value.
   {
     stored_value = std::move(v);
     return *this;
   }
operator=() [11/14]
value & json::value::operator= (const json::array & v)
Convert the value to array, then assigns v.
Definition at line 184 of file value.cc.
References stored_value.
   {
     stored_value = v;
     return *this;
   }
operator=() [12/14]
value & json::value::operator= (json::array && v)
Convert the value to array, then move assigns v. v becomes empty.
Definition at line 190 of file value.cc.
References stored_value.
   {
     stored_value = std::move(v);
     return *this;
   }
operator=() [13/14]
value & json::value::operator= (const json::object & v)
Convert the value to object, then assigns v.
Definition at line 196 of file value.cc.
References stored_value.
   {
     stored_value = v;
     return *this;
   }
operator=() [14/14]
value & json::value::operator= (json::object && v)
Convert the value to object, then move assigns v. v becomes empty.
Definition at line 202 of file value.cc.
References stored_value.
   {
     stored_value = std::move(v);
     return *this;
   }
operator==()
bool json::value::operator== (const value & other) const noexcept
True if both are the same type and values compare equal. False otherwise.
Definition at line 249 of file value.cc.
References json::array, json::mpl::variant< Ts >::as(), json::boolean, json::integer, json::null, json::object, json::real, stored_value, json::string, and type().
   {
     const auto t = type();
     if (t != other.type())
       return false;
     switch (t)
     {
     case value_type::null:
       return true;
     case value_type::integer:
       return stored_value.as<int64_t>() == other.stored_value.as<int64_t>();
     case value_type::real:
       return stored_value.as<double>() == other.stored_value.as<double>();
     case value_type::boolean:
       return stored_value.as<bool>() == other.stored_value.as<bool>();
     case value_type::string:
       return stored_value.as<json::string>() == other.stored_value.as<json::string>();
     case value_type::array:
       return stored_value.as<json::array>() == other.stored_value.as<json::array>();
     case value_type::object:
       return stored_value.as<json::object>() == other.stored_value.as<json::object>();
     default:
       return false;
     }
   }
operator>()
bool json::value::operator> (const value & other) const
True if both are the same type and this is greater than other. Invalid operation if different type.
Definition at line 244 of file value.cc.
   {
     return !(*this <= other);
   }
operator>=()
bool json::value::operator>= (const value & other) const
True if both are the same type and this is greater than or equal to other. Invalid operation if different type.
Definition at line 239 of file value.cc.
   {
     return !(*this < other);
   }
stored_bool() [1/2]
bool & json::value::stored_bool ()
If boolean, returns a reference to the stored bool. Invalid operation otherwise.
Definition at line 441 of file value.cc.
References json::mpl::variant< Ts >::as(), is_real(), and stored_value.
   {
     if (is_real())
       return stored_value.as<bool>();
     else
       throw invalid_operation{ "Value not compatible with stored_bool" };
   }
stored_bool() [2/2]
const bool & json::value::stored_bool () const
If boolean, returns a reference to the stored bool. Invalid operation otherwise.
Definition at line 449 of file value.cc.
References json::mpl::variant< Ts >::as(), is_real(), and stored_value.
   {
     if (is_real())
       return stored_value.as<bool>();
     else
       throw invalid_operation{ "Value not compatible with stored_bool" };
   }
stored_double() [1/2]
double & json::value::stored_double ()
If real, returns a reference to the stored double. Invalid operation otherwise.
Definition at line 425 of file value.cc.
References json::mpl::variant< Ts >::as(), is_real(), and stored_value.
   {
     if (is_real())
       return stored_value.as<double>();
     else
       throw invalid_operation{ "Value not compatible with stored_double" };
   }
stored_double() [2/2]
const double & json::value::stored_double () const
If real, returns a reference to the stored double. Invalid operation otherwise.
Definition at line 433 of file value.cc.
References json::mpl::variant< Ts >::as(), is_real(), and stored_value.
   {
     if (is_real())
       return stored_value.as<double>();
     else
       throw invalid_operation{ "Value not compatible with stored_double" };
   }
stored_int() [1/2]
int64_t & json::value::stored_int ()
If integer, returns a reference to the stored int64_t. Invalid operation otherwise.
Definition at line 409 of file value.cc.
References json::mpl::variant< Ts >::as(), is_int(), and stored_value.
   {
     if (is_int())
       return stored_value.as<int64_t>();
     else
       throw invalid_operation{ "Value not compatible with stored_int" };
   }
stored_int() [2/2]
const int64_t & json::value::stored_int () const
If integer, returns a reference to the stored int64_t. Invalid operation otherwise.
Definition at line 417 of file value.cc.
References json::mpl::variant< Ts >::as(), is_int(), and stored_value.
   {
     if (is_int())
       return stored_value.as<int64_t>();
     else
       throw invalid_operation{ "Value not compatible with stored_int" };
   }
swap()
void json::value::swap (value & other) noexcept
Swaps the content of two values.
Definition at line 208 of file value.cc.
References stored_value.
Referenced by std::swap().
   {
     auto temp = std::move(other.stored_value);
     other.stored_value = std::move(stored_value);
     stored_value = std::move(temp);
   }
type()
json::value_type json::value::type () const noexcept
Returns the type of the value.
Definition at line 505 of file value.cc.
References json::mpl::variant< Ts >::index(), and stored_value.
Referenced by operator==(), and json::writer::write().
   {
     // stored_value.index() will return
     //    null    = -1
     //    integer =  0
     //    real    =  1
     //    boolean =  2
     //    string  =  3
     //    array   =  4
     //    object  =  5
     // We have to map this to the enum value_type, where
     //    null    =  0
     //    integer =  1
     //    real    =  2
     //    boolean =  3
     //    string  =  4
     //    array   =  5
     //    object  =  6
     // So just add 1 to the return value of index() to get the current type in the enum
     return static_cast<json::value_type>(stored_value.index() + 1);
   }
Member Data Documentation
null
const value json::value::null static
Constant null value returned by const subscript operator of object on failure.
Definition at line 206 of file value.hh.
Referenced by json::object::operator[]().
stored_value
mpl::variant< int64_t, double, bool, json::string, json::array, json::object > json::value::stored_value private
Variant with the possible value types the class may have.
Definition at line 378 of file value.hh.
Referenced by as_array(), as_bool(), as_c_string(), as_double(), as_float(), as_int(), as_int64(), as_object(), as_string(), as_uint(), as_uint64(), is_array(), is_bool(), is_int(), is_null(), is_object(), is_real(), is_string(), operator<(), operator=(), operator==(), stored_bool(), stored_double(), stored_int(), swap(), type(), and value().
The documentation for this class was generated from the following files:
value.hh
value.cc