Json: json::string_key_literals Namespace Reference
json::string_key_literals Namespace Reference
Functions
constexpr static_string operator"" _ss (const char *str, size_t length) noexcept
Construct static_string from [str, str + length)
constexpr static_wstring operator"" _ss (const wchar_t *str, size_t length) noexcept
Construct static_wstring from [str, str + length)
constexpr static_u16string operator"" _ss (const char16_t *str, size_t length) noexcept
Construct static_u16string from [str, str + length)
constexpr static_u32string operator"" _ss (const char32_t *str, size_t length) noexcept
Construct static_u32string from [str, str + length)
string_key operator"" _sk (const char *str, size_t length) noexcept
Construct string_key from [str, str + length). The object is a view of the string literal, and allocates no memory.
wstring_key operator"" _sk (const wchar_t *str, size_t length) noexcept
Construct wstring_key from [str, str + length). The object is a view of the string literal, and allocates no memory.
u16string_key operator"" _sk (const char16_t *str, size_t length) noexcept
Construct u16string_key from [str, str + length). The object is a view of the string literal, and allocates no memory.
u32string_key operator"" _sk (const char32_t *str, size_t length) noexcept
Construct u16string_key from [str, str + length). The object is a view of the string literal, and allocates no memory.
Function Documentation
operator"" _sk() [1/4]
string_key json::string_key_literals::operator"" _sk (const char * str, size_t length) inline noexcept
Construct string_key from [str, str + length). The object is a view of the string literal, and allocates no memory.
Definition at line 718 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::length(), and json::basic_string_key< CharT, Traits, Allocator >::str.
     {
       return string_key{ static_string{ str, length } };
     }
operator"" _sk() [2/4]
wstring_key json::string_key_literals::operator"" _sk (const wchar_t * str, size_t length) inline noexcept
Construct wstring_key from [str, str + length). The object is a view of the string literal, and allocates no memory.
Definition at line 724 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::length(), and json::basic_string_key< CharT, Traits, Allocator >::str.
     {
       return wstring_key{ static_wstring{ str, length } };
     }
operator"" _sk() [3/4]
u16string_key json::string_key_literals::operator"" _sk (const char16_t * str, size_t length) inline noexcept
Construct u16string_key from [str, str + length). The object is a view of the string literal, and allocates no memory.
Definition at line 730 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::length(), and json::basic_string_key< CharT, Traits, Allocator >::str.
     {
       return u16string_key{ static_u16string{ str, length } };
     }
operator"" _sk() [4/4]
u32string_key json::string_key_literals::operator"" _sk (const char32_t * str, size_t length) inline noexcept
Construct u16string_key from [str, str + length). The object is a view of the string literal, and allocates no memory.
Definition at line 736 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::length(), and json::basic_string_key< CharT, Traits, Allocator >::str.
     {
       return u32string_key{ static_u32string{ str, length } };
     }
operator"" _ss() [1/4]
constexpr static_string json::string_key_literals::operator"" _ss (const char * str, size_t length) noexcept
Construct static_string from [str, str + length)
Definition at line 694 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::length(), and json::basic_string_key< CharT, Traits, Allocator >::str.
     {
       return static_string{ str, length };
     }
operator"" _ss() [2/4]
constexpr static_wstring json::string_key_literals::operator"" _ss (const wchar_t * str, size_t length) noexcept
Construct static_wstring from [str, str + length)
Definition at line 700 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::length(), and json::basic_string_key< CharT, Traits, Allocator >::str.
     {
       return static_wstring{ str, length };
     }
operator"" _ss() [3/4]
constexpr static_u16string json::string_key_literals::operator"" _ss (const char16_t * str, size_t length) noexcept
Construct static_u16string from [str, str + length)
Definition at line 706 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::length(), and json::basic_string_key< CharT, Traits, Allocator >::str.
     {
       return static_u16string{ str, length };
     }
operator"" _ss() [4/4]
constexpr static_u32string json::string_key_literals::operator"" _ss (const char32_t * str, size_t length) noexcept
Construct static_u32string from [str, str + length)
Definition at line 712 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::length(), and json::basic_string_key< CharT, Traits, Allocator >::str.
     {
       return static_u32string{ str, length };
     }