Json: json::writer Namespace Reference
json::writer Namespace Reference
Functions
json::string write (const json::value &val, const json::string &indentation, size_t indentation_level)
json::string write_int (int64_t i)
json::string write_float (double d)
json::string write_bool (bool b)
bool is_control_character (char c)
json::string write_string (const char *begin, const char *end)
json::string write_string (const json::string &str)
json::string write_string (const json::string_key &str)
json::string indent (const json::string &indentation, size_t indentation_level)
json::string write_array (const json::array &a, const json::string &indentation, size_t indentation_level)
json::string write_object (const json::object &a, const json::string &indentation, size_t indentation_level)
json::string write (const json::value &val, const json::string &indentation="\")
Writes a json::value in json format to a string.
json::string write (const json::object &val, const json::string &indentation="\")
Writes a json::object in json format to a string.
std::ostream & write (std::ostream &os, const json::value &val, const json::string &indentation="\")
Writes a json::value in json format to a standard stream Same as os << write(val, indentation)
std::ostream & write (std::ostream &os, const json::object &val, const json::string &indentation="\")
Writes a json::object in json format to a standard stream Same as os << write(val, indentation)
Function Documentation
indent()
json::string json::writer::indent (const json::string & indentation, size_t indentation_level)
Definition at line 146 of file writer.cc.
Referenced by write_array(), and write_object().
     {
       json::string result;
       result.reserve(indentation.size() * indentation_level);
       for (size_t i = 0; i < indentation_level; ++i)
         result += indentation;
       return result;
     }
is_control_character()
bool json::writer::is_control_character (char c)
Definition at line 60 of file writer.cc.
Referenced by write_string().
     {
       return
         c == '"'  || c == '\\' || c == '/' ||
         c == '\b' || c == '\f' || c == '\n' ||
         c == '\r' || c == '\t';
     }
write() [1/5]
json::string json::writer::write (const json::value & val, const json::string & indentation, size_t indentation_level)
Definition at line 239 of file writer.cc.
References json::array, json::value::as_array(), json::value::as_bool(), json::value::as_double(), json::value::as_int64(), json::value::as_object(), json::value::as_string(), json::boolean, json::integer, json::null, json::object, json::real, json::string, json::value::type(), write_array(), write_bool(), write_float(), write_int(), write_object(), and write_string().
Referenced by operator<<(), write(), write_array(), and write_object().
     {
       switch (val.type())
       {
         case value_type::null:
         {
           return "null";
         }
         case value_type::integer:
         {
           return write_int(val.as_int64());
         }
         case value_type::real:
         {
           return write_float(val.as_double());
         }
         case value_type::boolean:
         {
           return write_bool(val.as_bool());
         }
         case value_type::string:
         {
           return write_string(val.as_string());
         }
         case value_type::array:
         {
           return write_array(val.as_array(), indentation, indentation_level);
         }
         case value_type::object:
         {
           return write_object(val.as_object(), indentation, indentation_level);
         }
       }
       assert(false); // Control should never reach this point
       return{};
     }
write() [2/5]
JSON_API json::string json::writer::write (const json::value & val, const json::string & indentation)
Writes a json::value in json format to a string.
Definition at line 276 of file writer.cc.
References write().
     {
       return write(val, indentation, 0);
     }
write() [3/5]
JSON_API json::string json::writer::write (const json::object & val, const json::string & indentation)
Writes a json::object in json format to a string.
Definition at line 281 of file writer.cc.
References write_object().
     {
       return write_object(val, indentation, 0);
     }
write() [4/5]
JSON_API std::ostream & json::writer::write (std::ostream & os, const json::value & val, const json::string & indentation)
Writes a json::value in json format to a standard stream Same as os << write(val, indentation)
Definition at line 286 of file writer.cc.
References write().
     {
       return os << write(val, indentation);
     }
write() [5/5]
JSON_API std::ostream & json::writer::write (std::ostream & os, const json::object & val, const json::string & indentation)
Writes a json::object in json format to a standard stream Same as os << write(val, indentation)
Definition at line 291 of file writer.cc.
References write().
     {
       return os << write(val, indentation);
     }
write_array()
json::string json::writer::write_array (const json::array & a, const json::string & indentation, size_t indentation_level)
Definition at line 158 of file writer.cc.
References indent(), and write().
Referenced by write().
     {
       json::string out;
       // [ to start array
       out += '[';
       // Write a newline only if the array is not empty so that empty array looks like []
       if (!a.empty())
         out += '\n';
       // Increment the indentation level
       indentation_level++;
       // Precompute body indentation to avoid computing it in a loop
       const auto body_indentation = indent(indentation, indentation_level);
       // Write every value of the array in a different line, separated with comma ,
       for (auto it = a.begin(); it != a.end(); ++it)
       {
         out += body_indentation;
         out += write(*it, indentation, indentation_level);
         // Write a comma only if this is not the last element
         if (it + 1 != a.end())
           out += ',';
         out += '\n';
       }
       indentation_level--;
       // Close the array with ]
       out += indent(indentation, indentation_level);
       out += ']';
       return out;
     }
write_bool()
json::string json::writer::write_bool (bool b)
Definition at line 51 of file writer.cc.
Referenced by write().
     {
       if (b)
         return "true";
       else
         return "false";
     }
write_float()
json::string json::writer::write_float (double d)
Definition at line 38 of file writer.cc.
References string_printf.
Referenced by write().
     {
       char buffer[64] = { 0 };
       const auto chars_written = string_printf(buffer, "%f", d);
       const char * end = buffer + chars_written;
       // Remove the trailing zeros (eg: 2.250000 becomes 2.25)
       while (*(end - 1) == '0')
         end--;
       return json::string{ static_cast<const char *>(buffer), end };
     }
write_int()
json::string json::writer::write_int (int64_t i)
Definition at line 23 of file writer.cc.
References string_printf.
Referenced by write().
     {
       char buffer[32] = { 0 };
       // 64 bit integer is long long in Microsoft compiler and long in gcc and clang
       #if _MSC_VER
         const auto chars_written = string_printf(buffer, "%lld", i);
       #else
         const auto chars_written = string_printf(buffer, "%ld", i);
       #endif
       return json::string{ buffer, buffer + chars_written };
     }
write_object()
json::string json::writer::write_object (const json::object & a, const json::string & indentation, size_t indentation_level)
Definition at line 195 of file writer.cc.
References json::object::begin(), json::object::empty(), json::object::end(), indent(), write(), and write_string().
Referenced by write().
     {
       json::string out;
       // { to start object
       out += '{';
       // Write a newline only if the object is not empty so that empty object looks like {}
       if (!a.empty())
         out += '\n';
       // Increment the indentation level
       indentation_level++;
       // Precompute body indentation to avoid computing it in a loop
       const auto body_indentation = indent(indentation, indentation_level);
       // Write every value of the array in a different line, separated with comma ,
       for (auto it = a.begin(); it != a.end(); ++it)
       {
         out += body_indentation;
         out += write_string(it->first);
         out += " : ";
         if (it->second.is_array() || it->second.is_object())
         {
           out += '\n';
           out += body_indentation;
         }
         out += write(it->second, indentation, indentation_level);
         // Write a comma only if this is not the last element
         if (std::next(it) != a.end())
           out += ',';
         out += '\n';
       }
       indentation_level--;
       // Close the object with }
       out += indent(indentation, indentation_level);
       out += '}';
       return out;
     }
write_string() [1/3]
json::string json::writer::write_string (const char * begin, const char * end)
Definition at line 68 of file writer.cc.
References is_control_character().
Referenced by write(), write_object(), and write_string().
     {
       json::string out;
       // Reserve space for the string, the beginning and end quotation marks " and the backslashes \ of the control characters
       out.reserve(end - begin + 2 + std::count_if(begin, end, is_control_character));
       out += '\"';
       out.append(begin, end);
       // Process control characters of the string
       for (auto it = out.begin() + 1; it != out.end(); ++it)
       {
         const char c = *it;
         switch (c)
         {
           // For " and \ just append the control character \ before
         case '"':
         case '\\':
         {
           // Insert returns an iterator to the inserted character, so add 1 in order to skip the next
           // character as well. Otherwise it enters in an infinite loop as it checks the same control
           // character once and again
           it = out.insert(it, '\\') + 1;
           break;
         }
         case '\b':
         {
           // Append the \ before
           it = out.insert(it, '\\') + 1;
           // Change the control character for the printable character that represents it
           *it = 'b';
           break;
         }
         case '\f':
         {
           it = out.insert(it, '\\') + 1;
           *it = 'f';
           break;
         }
         case '\n':
         {
           it = out.insert(it, '\\') + 1;
           *it = 'n';
           break;
         }
         case '\r':
         {
           it = out.insert(it, '\\') + 1;
           *it = 'r';
           break;
         }
         case '\t':
         {
           it = out.insert(it, '\\') + 1;
           *it = 't';
           break;
         }
         }
       }
       out += '\"';
       return out;
     }
write_string() [2/3]
json::string json::writer::write_string (const json::string & str)
Definition at line 134 of file writer.cc.
References write_string().
     {
       return write_string(str.c_str(), str.c_str() + str.size());
     }
write_string() [3/3]
json::string json::writer::write_string (const json::string_key & str)
Definition at line 140 of file writer.cc.
References json::basic_string_key< CharT, Traits, Allocator >::c_str(), json::basic_string_key< CharT, Traits, Allocator >::size(), and write_string().
     {
       return write_string(str.c_str(), str.c_str() + str.size());
     }