Json: json Namespace Reference
json Namespace Reference
Namespaces
mpl
parser
string_key_literals
writer
Classes
class basic_static_string
Representation of a constant string that will outlive the json::value that is using it (usually a string literal). A json::value can use static strings as keys for objects in order to avoid allocations if the user knows for sure that the string will not be destroyed while the value is being used.
class basic_string_key
Representation of a string key for an associative container. It's used as the key of the map in json::object. Supports standard traits and allocators, as well as transparent comparison with c strings and std::basic_strings. If constructed from a static_string, the class will keep a reference to the original string instead of allocating a copy, acting as an string_view, thus saving a heap operation if the user is sure that the static string will outlive the string_key. The string is immutable. After being constructed, it can't be mutated in any way.
class invalid_operation
Thrown when trying to access a value as a type different to its own (eg: using as_int on an array type) or when comparing for inequality two values of different types.
class object
Data structure representing json object. An object is an unordered set of name/value pairs. An object begins with { (left brace) and ends with } (right brace). Each name is followed by : (colon) and the name/value pairs are separated by , (comma). http://www.json.org/.
class value
Data structure representing a json value http://www.json.org.
Typedefs
template<typename T >
using allocator = std::allocator< T >
Allocator type used by all the json functions and classes.
using string = std::basic_string< char, std::char_traits< char >, json::allocator< char > >
String type used by all the json functions and classes.
template<typename T >
using vector = std::vector< T, json::allocator< T > >
Vector type used by all the json functions and classes.
template<typename Key , typename Value >
using map = std::map< Key, Value, std::less<>, json::allocator< std::pair< const Key, Value > >>
Map type used by all the json functions and classes.
using static_string = basic_static_string< char >
Typedef for basic_static_string of chars (the same way std::string is std::basic_string<char>)
using static_wstring = basic_static_string< wchar_t >
Typedef for basic_static_string of wchar_t.
using static_u16string = basic_static_string< char16_t >
Typedef for basic_static_string of char16_t.
using static_u32string = basic_static_string< char32_t >
Typedef for basic_static_string of char32_t.
using string_key = basic_string_key< char >
Typedef for basic_string_key of chars (the same way std::string is std::basic_string<char>)
using wstring_key = basic_string_key< wchar_t >
Typedef for basic_string_key of wchar_t.
using u16string_key = basic_string_key< char16_t >
Typedef for basic_string_key of char16_t.
using u32string_key = basic_string_key< char32_t >
Typedef for basic_string_key of char32_t.
using array = json::vector< json::value >
Data structure representing a json array. An array is an ordered collection of values. An array begins with [ (left bracket) and ends with ] (right bracket). Values are separated by , (comma). http://www.json.org/.
Enumerations
enum value_type {
value_type::null = 0, value_type::integer = 1, value_type::real = 2, value_type::boolean = 3,
value_type::string = 4, value_type::array = 5, value_type::object = 6
}
Enum with the possible types a json::value may hold.
Functions
template<typename T >
bool points_inside (const void *p, const T &obj)
True if p points to obj or a member of obj True if p points to an address in memory in the range [&obj, (char *)&obj + sizeof(obj))
template<typename CharT , typename Traits , typename Allocator >
CharT * release (std::basic_string< CharT, Traits, Allocator > &s)
Makes a string release the ownership over its dynamic memory and return a pointer to it.
template<typename CharT , typename Traits , typename Allocator >
CharT * release (std::basic_string< CharT, Traits, Allocator > &&s)
Makes a string release the ownership over its dynamic memory and return a pointer to it.
template<typename T , typename Allocator >
T * release (std::vector< T, Allocator > &v)
Makes a vector release the ownership over its dynamic memory and return a pointer to it.
template<typename T , typename Allocator >
T * release (std::vector< T, Allocator > &&v)
Makes a vector release the ownership over its dynamic memory and return a pointer to it.
template<typename T , typename Deleter >
std::unique_ptr< T, Deleter >::pointer release (std::unique_ptr< T, Deleter > &p)
Makes a unique_ptr release the ownership over its dynamic memory. Same as p.release()
template<typename T , typename Deleter >
std::unique_ptr< T, Deleter >::pointer release (std::unique_ptr< T, Deleter > &&p)
Makes a unique_ptr release the ownership over its dynamic memory. Same as p.release()
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator== (const basic_string_key< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
True if both strings are equal.
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator!= (const basic_string_key< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
True if both strings are not equal.
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator< (const basic_string_key< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
Lexicographically compares both strings.
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator<= (const basic_string_key< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
Lexicographically compares both strings.
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator> (const basic_string_key< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
Lexicographically compares both strings.
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator>= (const basic_string_key< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
Lexicographically compares both strings.
template<typename CharT , typename Traits , typename Allocator >
bool operator== (const basic_string_key< CharT, Traits, Allocator > &a, const CharT *b) noexcept
Overload of comparison operators for c strings.
template<typename CharT , typename Traits , typename Allocator >
bool operator!= (const basic_string_key< CharT, Traits, Allocator > &a, const CharT *b) noexcept
template<typename CharT , typename Traits , typename Allocator >
bool operator< (const basic_string_key< CharT, Traits, Allocator > &a, const CharT *b) noexcept
template<typename CharT , typename Traits , typename Allocator >
bool operator<= (const basic_string_key< CharT, Traits, Allocator > &a, const CharT *b) noexcept
template<typename CharT , typename Traits , typename Allocator >
bool operator> (const basic_string_key< CharT, Traits, Allocator > &a, const CharT *b) noexcept
template<typename CharT , typename Traits , typename Allocator >
bool operator>= (const basic_string_key< CharT, Traits, Allocator > &a, const CharT *b) noexcept
template<typename CharT , typename Traits , typename Allocator >
bool operator== (const CharT *a, const basic_string_key< CharT, Traits, Allocator > &b) noexcept
template<typename CharT , typename Traits , typename Allocator >
bool operator!= (const CharT *a, const basic_string_key< CharT, Traits, Allocator > &b) noexcept
template<typename CharT , typename Traits , typename Allocator >
bool operator< (const CharT *a, const basic_string_key< CharT, Traits, Allocator > &b) noexcept
template<typename CharT , typename Traits , typename Allocator >
bool operator<= (const CharT *a, const basic_string_key< CharT, Traits, Allocator > &b) noexcept
template<typename CharT , typename Traits , typename Allocator >
bool operator> (const CharT *a, const basic_string_key< CharT, Traits, Allocator > &b) noexcept
template<typename CharT , typename Traits , typename Allocator >
bool operator>= (const CharT *a, const basic_string_key< CharT, Traits, Allocator > &b) noexcept
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator== (const basic_string_key< CharT, Traits, Allocator1 > &a, const std::basic_string< CharT, Traits, Allocator2 > &b) noexcept
Overload of comparison operators for std::basic_string.
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator!= (const basic_string_key< CharT, Traits, Allocator1 > &a, const std::basic_string< CharT, Traits, Allocator2 > &b) noexcept
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator< (const basic_string_key< CharT, Traits, Allocator1 > &a, const std::basic_string< CharT, Traits, Allocator2 > &b) noexcept
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator<= (const basic_string_key< CharT, Traits, Allocator1 > &a, const std::basic_string< CharT, Traits, Allocator2 > &b) noexcept
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator> (const basic_string_key< CharT, Traits, Allocator1 > &a, const std::basic_string< CharT, Traits, Allocator2 > &b) noexcept
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator>= (const basic_string_key< CharT, Traits, Allocator1 > &a, const std::basic_string< CharT, Traits, Allocator2 > &b) noexcept
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator== (const std::basic_string< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator!= (const std::basic_string< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator< (const std::basic_string< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator<= (const std::basic_string< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator> (const std::basic_string< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 >
bool operator>= (const std::basic_string< CharT, Traits, Allocator1 > &a, const basic_string_key< CharT, Traits, Allocator2 > &b) noexcept
Typedef Documentation
allocator
template<typename T > using json::allocator = typedef std::allocator<T>
Allocator type used by all the json functions and classes.
Definition at line 15 of file config.hh.
array
using json::array = typedef json::vector<json::value>
Data structure representing a json array. An array is an ordered collection of values. An array begins with [ (left bracket) and ends with ] (right bracket). Values are separated by , (comma). http://www.json.org/.
Definition at line 39 of file value.hh.
map
template<typename Key , typename Value > using json::map = typedef std::map<Key, Value, std::less<>, json::allocator<std::pair<const Key, Value> >>
Map type used by all the json functions and classes.
Definition at line 26 of file config.hh.
static_string
using json::static_string = typedef basic_static_string<char>
Typedef for basic_static_string of chars (the same way std::string is std::basic_string<char>)
Definition at line 39 of file string_key.hh.
static_u16string
using json::static_u16string = typedef basic_static_string<char16_t>
Typedef for basic_static_string of char16_t.
Definition at line 43 of file string_key.hh.
static_u32string
using json::static_u32string = typedef basic_static_string<char32_t>
Typedef for basic_static_string of char32_t.
Definition at line 45 of file string_key.hh.
static_wstring
using json::static_wstring = typedef basic_static_string<wchar_t>
Typedef for basic_static_string of wchar_t.
Definition at line 41 of file string_key.hh.
string
using json::string = typedef std::basic_string<char, std::char_traits<char>, json::allocator<char> >
String type used by all the json functions and classes.
Definition at line 18 of file config.hh.
string_key
using json::string_key = typedef basic_string_key<char>
Typedef for basic_string_key of chars (the same way std::string is std::basic_string<char>)
Definition at line 309 of file string_key.hh.
u16string_key
using json::u16string_key = typedef basic_string_key<char16_t>
Typedef for basic_string_key of char16_t.
Definition at line 313 of file string_key.hh.
u32string_key
using json::u32string_key = typedef basic_string_key<char32_t>
Typedef for basic_string_key of char32_t.
Definition at line 315 of file string_key.hh.
vector
template<typename T > using json::vector = typedef std::vector<T, json::allocator<T> >
Vector type used by all the json functions and classes.
Definition at line 22 of file config.hh.
wstring_key
using json::wstring_key = typedef basic_string_key<wchar_t>
Typedef for basic_string_key of wchar_t.
Definition at line 311 of file string_key.hh.
Enumeration Type Documentation
value_type
enum json::value_type strong
Enum with the possible types a json::value may hold.
Enumerator
null
integer
real
boolean
string
array
object
Definition at line 14 of file value.hh.
   {
     null    = 0,
     integer = 1,
     real    = 2,
     boolean = 3,
     string  = 4,
     array   = 5,
     object  = 6
   };
Function Documentation
operator!=() [1/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator!= (const basic_string_key< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
True if both strings are not equal.
Definition at line 517 of file string_key.inl.
   {
     return !(a == b);
   }
operator!=() [2/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator!= (const basic_string_key< CharT, Traits, Allocator > & a, const CharT * b) inline noexcept
Definition at line 553 of file string_key.inl.
   {
     return !(a == b);
   }
operator!=() [3/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator!= (const CharT * a, const basic_string_key< CharT, Traits, Allocator > & b) inline noexcept
Definition at line 589 of file string_key.inl.
   {
     return b != a;
   }
operator!=() [4/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator!= (const basic_string_key< CharT, Traits, Allocator1 > & a, const std::basic_string< CharT, Traits, Allocator2 > & b) inline noexcept
Definition at line 625 of file string_key.inl.
   {
     return !(a == b);
   }
operator!=() [5/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator!= (const std::basic_string< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
Definition at line 661 of file string_key.inl.
   {
     return !(a == b);
   }
operator<() [1/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator< (const basic_string_key< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
Lexicographically compares both strings.
Definition at line 523 of file string_key.inl.
   {
     return std::lexicographical_compare(a.begin(), a.end(), b.begin(), b.end(), Traits::lt);
   }
operator<() [2/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator< (const basic_string_key< CharT, Traits, Allocator > & a, const CharT * b) inline noexcept
Definition at line 559 of file string_key.inl.
   {
     return Traits::compare(a.c_str(), b, a.size() + 1) < 0;
   }
operator<() [3/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator< (const CharT * a, const basic_string_key< CharT, Traits, Allocator > & b) inline noexcept
Definition at line 595 of file string_key.inl.
   {
     return Traits::compare(a, b.c_str(), b.size() + 1) < 0;
   }
operator<() [4/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator< (const basic_string_key< CharT, Traits, Allocator1 > & a, const std::basic_string< CharT, Traits, Allocator2 > & b) inline noexcept
Definition at line 631 of file string_key.inl.
   {
     return a < b.c_str();
   }
operator<() [5/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator< (const std::basic_string< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
Definition at line 667 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::c_str().
   {
     return a.c_str() < b;
   }
operator<=() [1/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator<= (const basic_string_key< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
Lexicographically compares both strings.
Definition at line 529 of file string_key.inl.
   {
     return (a == b) || (a < b);
   }
operator<=() [2/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator<= (const basic_string_key< CharT, Traits, Allocator > & a, const CharT * b) inline noexcept
Definition at line 565 of file string_key.inl.
   {
     return Traits::compare(a.c_str(), b, a.size() + 1) <= 0;
   }
operator<=() [3/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator<= (const CharT * a, const basic_string_key< CharT, Traits, Allocator > & b) inline noexcept
Definition at line 601 of file string_key.inl.
   {
     return Traits::compare(a, b.c_str(), b.size() + 1) <= 0;
   }
operator<=() [4/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator<= (const basic_string_key< CharT, Traits, Allocator1 > & a, const std::basic_string< CharT, Traits, Allocator2 > & b) inline noexcept
Definition at line 637 of file string_key.inl.
   {
     return a <= b.c_str();
   }
operator<=() [5/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator<= (const std::basic_string< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
Definition at line 673 of file string_key.inl.
References json::basic_string_key< CharT, Traits, Allocator >::c_str().
   {
     return a.c_str() <= b;
   }
operator==() [1/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator== (const basic_string_key< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
True if both strings are equal.
Definition at line 511 of file string_key.inl.
   {
     return a.size() == b.size() && std::equal(a.begin(), a.end(), b.begin(), b.end(), Traits::eq);
   }
operator==() [2/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator== (const basic_string_key< CharT, Traits, Allocator > & a, const CharT * b) inline noexcept
Overload of comparison operators for c strings.
Definition at line 547 of file string_key.inl.
   {
     return Traits::compare(a.c_str(), b, a.size() + 1) == 0;
   }
operator==() [3/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator== (const CharT * a, const basic_string_key< CharT, Traits, Allocator > & b) inline noexcept
Definition at line 583 of file string_key.inl.
   {
     return b == a;
   }
operator==() [4/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator== (const basic_string_key< CharT, Traits, Allocator1 > & a, const std::basic_string< CharT, Traits, Allocator2 > & b) inline noexcept
Overload of comparison operators for std::basic_string.
Definition at line 619 of file string_key.inl.
   {
     return a.size() == b.size() && std::equal(a.begin(), a.end(), b.begin(), b.end());
   }
operator==() [5/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator== (const std::basic_string< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
Definition at line 655 of file string_key.inl.
   {
     return b == a;
   }
operator>() [1/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator> (const basic_string_key< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
Lexicographically compares both strings.
Definition at line 535 of file string_key.inl.
   {
     return !(a <= b);
   }
operator>() [2/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator> (const basic_string_key< CharT, Traits, Allocator > & a, const CharT * b) inline noexcept
Definition at line 571 of file string_key.inl.
   {
     return Traits::compare(a.c_str(), b, a.size() + 1) > 0;
   }
operator>() [3/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator> (const CharT * a, const basic_string_key< CharT, Traits, Allocator > & b) inline noexcept
Definition at line 607 of file string_key.inl.
   {
     return Traits::compare(a, b.c_str(), b.size() + 1) > 0;
   }
operator>() [4/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator> (const basic_string_key< CharT, Traits, Allocator1 > & a, const std::basic_string< CharT, Traits, Allocator2 > & b) inline noexcept
Definition at line 643 of file string_key.inl.
   {
     return a > b.c_str();
   }
operator>() [5/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator> (const std::basic_string< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
Definition at line 679 of file string_key.inl.
   {
     return a.c_str() > b;
   }
operator>=() [1/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator>= (const basic_string_key< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
Lexicographically compares both strings.
Definition at line 541 of file string_key.inl.
   {
     return !(a < b);
   }
operator>=() [2/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator>= (const basic_string_key< CharT, Traits, Allocator > & a, const CharT * b) inline noexcept
Definition at line 577 of file string_key.inl.
   {
     return Traits::compare(a.c_str(), b, a.size() + 1) >= 0;
   }
operator>=() [3/5]
template<typename CharT , typename Traits , typename Allocator > bool json::operator>= (const CharT * a, const basic_string_key< CharT, Traits, Allocator > & b) inline noexcept
Definition at line 613 of file string_key.inl.
   {
     return Traits::compare(a, b.c_str(), b.size() + 1) >= 0;
   }
operator>=() [4/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator>= (const basic_string_key< CharT, Traits, Allocator1 > & a, const std::basic_string< CharT, Traits, Allocator2 > & b) inline noexcept
Definition at line 649 of file string_key.inl.
   {
     return a >= b.c_str();
   }
operator>=() [5/5]
template<typename CharT , typename Traits , typename Allocator1 , typename Allocator2 > bool json::operator>= (const std::basic_string< CharT, Traits, Allocator1 > & a, const basic_string_key< CharT, Traits, Allocator2 > & b) inline noexcept
Definition at line 685 of file string_key.inl.
   {
     return a.c_str() >= b;
   }
points_inside()
template<typename T > bool json::points_inside (const void * p, const T & obj)
True if p points to obj or a member of obj True if p points to an address in memory in the range [&obj, (char *)&obj + sizeof(obj))
Definition at line 5 of file release.inl.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::basic_string_key(), and release().
   {
     const auto begin = reinterpret_cast<const char *>(&obj);
     const auto end = begin + sizeof(T);
     const auto ptr = reinterpret_cast<const char *>(p);
     return (ptr >= begin) && (ptr < end);
   }
release() [1/6]
template<typename CharT , typename Traits , typename Allocator > CharT * json::release (std::basic_string< CharT, Traits, Allocator > & s)
Makes a string release the ownership over its dynamic memory and return a pointer to it.
Definition at line 15 of file release.inl.
Referenced by json::basic_string_key< CharT, Traits, Allocator >::basic_string_key(), and release().
   {
     return release(std::move(s));
   }
release() [2/6]
template<typename CharT , typename Traits , typename Allocator > CharT * json::release (std::basic_string< CharT, Traits, Allocator > && s)
Makes a string release the ownership over its dynamic memory and return a pointer to it.
Definition at line 21 of file release.inl.
References points_inside().
   {
     // If the string is a short string, it doesn't have any dynamic memory so there is no memory to release
     if (points_inside(s.data(), s))
       return nullptr;
     else
     {
       // Brief explanation of the dark magics behind this:
       // std::string is encapsulated such that the only way of making it release the ownership of
       // its dynamic memory without deleting it is moving it into another std::string. However, by
       // doing this the ownership is passed to another std::string so we still have the same problem
       // of the memory being owned by an RAII object that will delete it in its destructor.
       // The solution used below is moving the string into a buffer of bytes using placement new,
       // in order to make the source string release ownership over its memory without passing this
       // ownership to another RAII object, as an array of characters won't call the destructor of
       // std::string. At this point, the std::string object has released the ownership over its
       // dynamic memory, and the address of this memory can be trivially obtained by calling
       // std::string::data on the buffer.
       using string_t = std::basic_string<CharT, Traits, Allocator>;
       char buffer[sizeof(string_t)];
       ::new (buffer) string_t(std::move(s));
       // std::string::data is const in C++11. Non-const version wasn't added until C++14
       return const_cast<CharT *>(reinterpret_cast<string_t *>(buffer)->data());
     }
   }
release() [3/6]
template<typename T , typename Allocator > T * json::release (std::vector< T, Allocator > & v)
Makes a vector release the ownership over its dynamic memory and return a pointer to it.
Definition at line 49 of file release.inl.
References release().
   {
     return release(std::move(v));
   }
release() [4/6]
template<typename T , typename Allocator > T * json::release (std::vector< T, Allocator > && v)
Makes a vector release the ownership over its dynamic memory and return a pointer to it.
Definition at line 55 of file release.inl.
   {
     using vector_t = std::vector<T, Allocator>;
     char buffer[sizeof(vector_t)];
     ::new (buffer) vector_t(std::move(v));
     return reinterpret_cast<vector_t *>(buffer)->data();
   }
release() [5/6]
template<typename T , typename Deleter > std::unique_ptr< T, Deleter >::pointer json::release (std::unique_ptr< T, Deleter > & p)
Makes a unique_ptr release the ownership over its dynamic memory. Same as p.release()
Definition at line 64 of file release.inl.
References release().
   {
     return release(std::move(p));
   }
release() [6/6]
template<typename T , typename Deleter > std::unique_ptr< T, Deleter >::pointer json::release (std::unique_ptr< T, Deleter > && p)
Makes a unique_ptr release the ownership over its dynamic memory. Same as p.release()
Definition at line 70 of file release.inl.
   {
     return p.release();
   }