Json: value.cc File Reference
value.cc File Reference
#include "value.hh"
#include <cassert>
Namespaces
json
Functions
template<>
void std::swap (json::value &a, json::value &b)
Specialization of std::swap for json::value.
Function Documentation
swap()
template<> void std::swap (json::value & a, json::value & b)
Specialization of std::swap for json::value.
Definition at line 843 of file value.cc.
References json::value::swap(), and std::swap().
Referenced by std::swap().
   {
     a.swap(b);
   }